"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 31: Trace Comparator

Compare two execution traces (CSV) and find the first divergence.
"""

import sys
import os
import csv

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


# ---------------------------------------------------------------------------
# Trace Loading
# ---------------------------------------------------------------------------

def load_trace(filepath):
    """Load an execution trace from a CSV file.

    The CSV has a header row with column names (e.g., address, a, b, c, d,
    sp, flags). Each subsequent row is one trace step. All values are
    hex strings (with or without "0x" prefix).

    Args:
        filepath: path to the CSV file.

    Returns:
        A list of dicts, one per trace step. Each dict maps column name
        to an int value. For example:
            {"address": 0x0100, "a": 0x00, "b": 0x00, ...}
    """
    with open(filepath, newline="") as f:
        return [
            {key: int(value, 16) for key, value in row.items()}
            for row in csv.DictReader(f)
        ]


def load_trace_from_string(text):
    """Load a trace from a CSV string (for testing without files).

    Args:
        text: a string in CSV format (with header row).

    Returns:
        Same format as load_trace().
    """
    return [
        {key: int(value, 16) for key, value in row.items()}
        for row in csv.DictReader(text.splitlines())
    ]


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------

def compare_traces(trace_a, trace_b):
    """Compare two traces and find the first divergence.

    Args:
        trace_a: list of dicts (the reference/expected trace).
        trace_b: list of dicts (the test trace to compare against).

    Returns:
        None if the traces match completely (up to the shorter length).

        If a divergence is found, return a dict with:
            "step"     - int, the 0-based step index where divergence occurs
            "expected" - dict, the trace_a row at that step
            "got"      - dict, the trace_b row at that step
            "differs"  - list of column names that differ
    """
    for step, (expected, got) in enumerate(zip(trace_a, trace_b)):
        differs = [
            key for key in expected
            if key in got and expected[key] != got[key]
        ]
        if differs:
            return {
                "step": step,
                "expected": expected,
                "got": got,
                "differs": differs,
            }
    return None


def format_divergence(div):
    """Format a divergence dict into a human-readable string.

    Args:
        div: dict returned by compare_traces(), or None.

    Returns:
        A string describing the divergence. If div is None, return
        "Traces match."
    """
    if div is None:
        return "Traces match."

    step = div["step"]
    expected = div["expected"]
    got = div["got"]

    lines = [
        f"Traces diverge at step {step} (CSV line {step + 2}):",
        "",
    ]
    for key in div["differs"]:
        lines.append(
            f"  {key}: expected 0x{expected[key]:X}, got 0x{got[key]:X}"
        )
    lines.append("")
    lines.append("  expected row: " + ", ".join(
        f"{k}=0x{v:X}" for k, v in expected.items()))
    lines.append("  actual row:   " + ", ".join(
        f"{k}=0x{v:X}" for k, v in got.items()))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <trace_a.csv> <trace_b.csv>")
        sys.exit(1)

    trace_a = load_trace(sys.argv[1])
    trace_b = load_trace(sys.argv[2])

    if trace_a is None or trace_b is None:
        print("Error: load_trace() returned None.")
        sys.exit(1)

    print(f"Comparing {sys.argv[1]} vs {sys.argv[2]}...")
    div = compare_traces(trace_a, trace_b)
    print(format_divergence(div))


if __name__ == "__main__":
    main()
