"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 74: Vector Lifter With a Reference

Lift a guest vector ISA to host intrinsics, with scalar reference
implementations, and differentially test them at the boundaries.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


import math


def saturate(value, width=8, signed=False):
    """Clamp *value* into the range representable in *width* bits.

    Saturating arithmetic clamps at the boundary rather than wrapping. The RSP
    and MMI both do this, and a lifter that wraps produces plausible garbage.

    Args:
        value: the unclamped integer.
        width: bit width.
        signed: signed range if True.

    Returns:
        The clamped value.
    """
    if signed:
        lo, hi = -(1 << (width - 1)), (1 << (width - 1)) - 1
    else:
        lo, hi = 0, (1 << width) - 1
    return lo if value < lo else hi if value > hi else value


def vadd_sat(a, b, width=8, signed=False):
    """Elementwise saturating add of two equal-length vectors.

    Raises:
        ValueError: if the lengths differ. A silent zip() would truncate,
            which is the kind of quiet wrongness this whole unit is about.
    """
    if len(a) != len(b):
        raise ValueError(f"length mismatch: {len(a)} vs {len(b)}")
    return [saturate(x + y, width, signed) for x, y in zip(a, b)]


def flush_denormals(vec, enabled=True):
    """Model the guest's flush-to-zero mode.

    Many consoles flush denormals to zero in hardware; your host may not, and
    the difference is both a slowdown and a numeric difference.

    Args:
        vec: list of floats.
        enabled: whether FTZ is on.

    Returns:
        A new list, with denormals replaced by 0.0 (preserving sign) when
        enabled. Zero, infinity and NaN pass through untouched.
    """
    import sys
    if not enabled:
        return list(vec)

    out = []
    for v in vec:
        if v != 0.0 and math.isfinite(v) and abs(v) < sys.float_info.min:
            out.append(math.copysign(0.0, v))
        else:
            out.append(v)
    return out


def vmin(a, b, nan_wins=False):
    """Elementwise minimum with an explicit NaN policy.

    Args:
        a, b: equal-length lists of floats.
        nan_wins: if True, a NaN operand propagates. If False, the non-NaN
            operand is chosen (the common hardware behaviour).

    Returns:
        A new list.

    Raises:
        ValueError: on a length mismatch.
    """
    if len(a) != len(b):
        raise ValueError(f"length mismatch: {len(a)} vs {len(b)}")

    out = []
    for x, y in zip(a, b):
        x_nan, y_nan = math.isnan(x), math.isnan(y)
        if x_nan and y_nan:
            out.append(x)
        elif x_nan:
            out.append(x if nan_wins else y)
        elif y_nan:
            out.append(y if nan_wins else x)
        else:
            out.append(x if x < y else y)
    return out


def differential(op_a, op_b, cases):
    """Compare two implementations over a list of argument tuples.

    Comparison treats NaN as equal to NaN -- otherwise every case containing a
    NaN reports a spurious divergence and the real ones are lost in the noise.

    Args:
        op_a: reference callable.
        op_b: callable under test.
        cases: list of argument tuples.

    Returns:
        A dict with "total", "diverged" (count), and "failures" (list of dicts
        with "case", "expected" and "actual").
    """
    def same(x, y):
        if isinstance(x, float) and isinstance(y, float):
            if math.isnan(x) and math.isnan(y):
                return True
        if isinstance(x, list) and isinstance(y, list):
            return len(x) == len(y) and all(same(i, j) for i, j in zip(x, y))
        return x == y

    failures = []
    for case in cases:
        expected = op_a(*case)
        actual = op_b(*case)
        if not same(expected, actual):
            failures.append({"case": case, "expected": expected, "actual": actual})

    return {"total": len(cases), "diverged": len(failures), "failures": failures}


def interesting_floats():
    """Float values worth testing: zeros, denormals, infinities, NaN."""
    import sys
    tiny = sys.float_info.min
    return [0.0, -0.0, tiny, -tiny, tiny / 2, -tiny / 2,
            1.0, -1.0, float("inf"), float("-inf"), float("nan")]
