"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 106: Propose and Check

Take function-boundary proposals from any hypothesis generator and accept
or reject each one with structural and trace-based checkers.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


def check_alignment(proposal, alignment):
    """Is the proposed address correctly aligned?

    Returns:
        None if fine, otherwise a reason string.
    """
    addr = proposal["addr"]
    if addr % alignment:
        return f"0x{addr:X} is not {alignment}-byte aligned"
    return None


def check_in_range(proposal, code_range):
    """Is the address inside the code region?

    Args:
        proposal: dict with "addr".
        code_range: (lo, hi) inclusive.

    Returns:
        None if fine, otherwise a reason string.
    """
    lo, hi = code_range
    addr = proposal["addr"]
    if not lo <= addr <= hi:
        return f"0x{addr:X} is outside code range [0x{lo:X}, 0x{hi:X}]"
    return None


def check_not_mid_function(proposal, known):
    """Does this address fall inside a function we already know about?

    This is the check that caught civrev's over-hinting: a switch-table entry
    points into the middle of a real function, and hinting it splits that
    function in half.

    Args:
        proposal: dict with "addr".
        known: list of (start, size) tuples for functions already established.

    Returns:
        None if the address is not interior to any known function, otherwise a
        reason string. An address exactly at a known function's *start* is
        fine -- that is agreement, not a conflict.
    """
    addr = proposal["addr"]
    for start, size in known:
        if start < addr < start + size:
            return (f"0x{addr:X} is inside known function at 0x{start:X} "
                    f"(+0x{addr - start:X}); hinting it would split "
                    f"that function")
    return None


def check_observed(proposal, trace):
    """Did execution actually branch to this address?

    The strongest available evidence: a logged branch target is an observation,
    a pointer-shaped integer is a guess.

    Args:
        proposal: dict with "addr".
        trace: set or list of addresses execution actually reached.

    Returns:
        None if observed, otherwise a reason string. Not being observed is a
        weak signal, not proof of wrongness -- the caller decides how to weigh
        it, which is why this returns a reason rather than a verdict.
    """
    addr = proposal["addr"]
    if addr in set(trace):
        return None
    return f"0x{addr:X} was never reached during execution"


def evaluate(proposals, code_range, known, trace, alignment=4):
    """Run every check over every proposal.

    Args:
        proposals: list of dicts with "addr" and "source".
        code_range: (lo, hi) inclusive.
        known: list of (start, size) tuples.
        trace: observed addresses.
        alignment: required alignment.

    Returns:
        A dict with:
            "accepted"  - proposals passing every hard check, sorted by addr
            "rejected"  - list of dicts with "addr", "source" and "reasons"
            "observed"  - how many accepted proposals were also observed
            "by_source" - dict mapping source -> {"accepted", "rejected"}

    Alignment, range and mid-function are **hard** checks: failing any one
    rejects the proposal. Being unobserved is recorded but does not reject.
    """
    accepted, rejected = [], []
    by_source = {}
    observed = 0

    for proposal in proposals:
        source = proposal.get("source", "unknown")
        counts = by_source.setdefault(source, {"accepted": 0, "rejected": 0})

        reasons = [reason for reason in (
            check_alignment(proposal, alignment),
            check_in_range(proposal, code_range),
            check_not_mid_function(proposal, known),
        ) if reason is not None]

        if reasons:
            rejected.append({"addr": proposal["addr"], "source": source,
                             "reasons": reasons})
            counts["rejected"] += 1
        else:
            accepted.append(proposal)
            counts["accepted"] += 1
            if check_observed(proposal, trace) is None:
                observed += 1

    return {
        "accepted": sorted(accepted, key=lambda p: p["addr"]),
        "rejected": rejected,
        "observed": observed,
        "by_source": by_source,
    }


def format_evaluation(result):
    """Format an evaluation, per source."""
    lines = [f"accepted {len(result['accepted'])}, "
             f"rejected {len(result['rejected'])}, "
             f"{result['observed']} of the accepted were observed"]
    for source in sorted(result["by_source"]):
        counts = result["by_source"][source]
        lines.append(f"  {source:24s} +{counts['accepted']} -{counts['rejected']}")
    return "\n".join(lines)
