"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 88: Fold a Paging Instruction

Statically track a paged architecture's latched page so the paging
instruction emits nothing at all -- and assert the invariant that allows it.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


class PagingError(Exception):
    """Raised when the folding assumption does not hold."""


def resolve_targets(program):
    """Fold each PSET's page into the transfer instruction that follows it.

    An instruction is a dict:
        {"addr": int, "op": "PSET"|"JP"|"CALL"|"NOP"|...,
         "page": int or None, "offset": int or None}

    A transfer's absolute target is `(latched_page << 8) | offset`.

    Args:
        program: list of instruction dicts, in address order.

    Returns:
        A new list where every transfer has an added "target" key holding its
        resolved absolute address, and non-transfers have "target": None.
        PSET instructions are left in place -- emit() decides to drop them.

    Raises:
        PagingError: if a transfer is reached with no page ever latched. That
            is a genuinely unresolvable target, not something to guess at.
    """
    out = []
    page = None

    for insn in program:
        resolved = dict(insn)
        if insn["op"] == "PSET":
            page = insn["page"]
            resolved["target"] = None
        elif insn["op"] in ("JP", "CALL"):
            if page is None:
                raise PagingError(
                    f"transfer at 0x{insn['addr']:04X} with no page latched")
            resolved["target"] = (page << 8) | insn["offset"]
        else:
            resolved["target"] = None
        out.append(resolved)

    return out


def check_pset_invariant(program):
    """Is every PSET immediately followed by a control transfer?

    This is the assumption that lets PSET be folded away entirely, including
    its interrupt hold-off.

    Returns:
        A list of addresses of PSET instructions that are NOT followed by a
        transfer, sorted. Empty means the fold is sound.
    """
    violations = []
    for i, insn in enumerate(program):
        if insn["op"] != "PSET":
            continue
        if i + 1 >= len(program) or program[i + 1]["op"] not in ("JP", "CALL"):
            violations.append(insn["addr"])
    return sorted(violations)


def emit(program):
    """Emit C, dropping PSET entirely.

    Every instruction still gets a label, so a computed transfer can reach it.
    A PSET's body is empty -- a comment recording what was folded, nothing else.

    Returns:
        A list of source lines.

    Raises:
        PagingError: if the invariant does not hold. Emitting a fold whose
            precondition is unchecked is how a silent bug ships.
    """
    violations = check_pset_invariant(program)
    if violations:
        raise PagingError(
            "PSET not followed by a transfer at: "
            + ", ".join(f"0x{a:04X}" for a in violations))

    resolved = resolve_targets(program)
    lines = []
    for insn in resolved:
        lines.append(f"L_{insn['addr']:04X}: /* {insn['op']} */")
        if insn["op"] == "PSET":
            # Folded into the following transfer; nothing to emit.
            lines.append(f"    /* PSET 0x{insn['page']:02X} folded */")
        elif insn["op"] in ("JP", "CALL"):
            lines.append(f"    goto L_{insn['target']:04X};")
    return lines


def folding_report(program):
    """Summarise what folding achieved.

    Returns:
        A dict with:
            "instructions" - total
            "psets"        - how many PSETs
            "folded"       - how many emitted nothing (same as psets when the
                             invariant holds)
            "transfers"    - how many resolved transfers
    """
    psets = sum(1 for i in program if i["op"] == "PSET")
    transfers = sum(1 for i in program if i["op"] in ("JP", "CALL"))
    violations = check_pset_invariant(program) or []
    return {"instructions": len(program), "psets": psets,
            "folded": psets - len(violations), "transfers": transfers}
