"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 95: Harvard Memory Model

A memory layer for a CPU with disjoint code and data spaces, and the test
that catches an implementation which conflates them.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


class SpaceError(Exception):
    """Raised on an access outside a space."""


class HarvardMemory:
    """Two disjoint address spaces sharing no addresses.

    Attributes:
        rom: instruction space, read-only.
        ram: data and peripheral space.
    """

    def __init__(self, rom_size=0x10000, ram_size=0x200):
        self.rom = bytearray(rom_size)
        self.ram = bytearray(ram_size)
        self.io_handlers = {}     # ram address -> callable(value_or_None)

    def fetch(self, addr):
        """Fetch an instruction byte from ROM.

        Raises:
            SpaceError: if addr is outside ROM.
        """
        if not 0 <= addr < len(self.rom):
            raise SpaceError(f"ROM fetch at 0x{addr:X} is outside the space")
        return self.rom[addr]

    def ldc(self, addr):
        """Read a data byte from ROM -- the one instruction that crosses over.

        Raises:
            SpaceError: if addr is outside ROM.
        """
        if not 0 <= addr < len(self.rom):
            raise SpaceError(f"LDC at 0x{addr:X} is outside ROM")
        return self.rom[addr]

    def load(self, addr):
        """Read an operand byte from RAM, honouring any I/O handler.

        Raises:
            SpaceError: if addr is outside RAM.
        """
        if not 0 <= addr < len(self.ram):
            raise SpaceError(f"RAM load at 0x{addr:X} is outside the space")
        handler = self.io_handlers.get(addr)
        if handler is not None:
            return handler(None)
        return self.ram[addr]

    def store(self, addr, value):
        """Write an operand byte to RAM, honouring any I/O handler.

        Raises:
            SpaceError: if addr is outside RAM.
        """
        if not 0 <= addr < len(self.ram):
            raise SpaceError(f"RAM store at 0x{addr:X} is outside the space")
        handler = self.io_handlers.get(addr)
        if handler is not None:
            handler(value)
            return
        self.ram[addr] = value

    def map_io(self, addr, handler):
        """Register an I/O handler at a RAM address.

        The handler is called as handler(None) for a read and handler(value)
        for a write; its return value is used for reads.
        """
        self.io_handlers[addr] = handler


def detect_conflation(memory):
    """Check that the two spaces really are disjoint.

    Writes distinguishable values at the same numeric address in each space and
    verifies both survive. A flat implementation cannot pass this.

    Args:
        memory: a HarvardMemory.

    Returns:
        None if the spaces are disjoint, otherwise a detail string.
    """
    addr = min(len(memory.rom), len(memory.ram)) // 2

    memory.rom[addr] = 0xA5
    memory.store(addr, 0x5A)

    from_rom = memory.ldc(addr)
    from_ram = memory.load(addr)

    if from_rom == from_ram:
        return (f"address 0x{addr:X} reads 0x{from_rom:02X} from both spaces "
                f"-- ROM and RAM are the same storage")
    if from_rom != 0xA5:
        return f"ROM at 0x{addr:X} was overwritten by a RAM store"
    return None
