"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 73: Guest-Level Sampling Profiler

Sample the program counter and resolve each sample to a guest function,
producing a profile in the game's own terms rather than the host's.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


import bisect


def resolve(addr, functions):
    """Find the function containing *addr*.

    Args:
        addr: the sampled program counter.
        functions: list of (start, size, name) tuples, not necessarily sorted.

    Returns:
        The function name, or None if the address is in no known function.

    Use a binary search over the sorted starts -- a profiler that is O(n) per
    sample changes the thing it is measuring.
    """
    ordered = sorted(functions, key=lambda f: f[0])
    starts = [f[0] for f in ordered]
    i = bisect.bisect_right(starts, addr) - 1
    if i < 0:
        return None
    start, size, name = ordered[i]
    return name if addr < start + size else None


class Sampler:
    """Collects PC samples and resolves them to guest functions."""

    def __init__(self, functions):
        self.functions = sorted(functions, key=lambda f: f[0])
        self.samples = []
        self.unresolved = 0

    def sample(self, addr):
        """Record one sample.

        Samples that resolve to no function increment self.unresolved -- that
        count is itself informative, because it usually means execution left
        the recompiled image.
        """
        name = resolve(addr, self.functions)
        if name is None:
            self.unresolved += 1
        else:
            self.samples.append((addr, name))

    def profile(self):
        """Return a ranked profile.

        Returns:
            A list of dicts with "name", "samples" and "percent", sorted by
            sample count descending then name ascending. Percent is of total
            samples taken, including unresolved ones -- otherwise a build that
            spends half its time outside the image looks perfectly healthy.
        """
        total = len(self.samples) + self.unresolved
        counts = {}
        for _addr, name in self.samples:
            counts[name] = counts.get(name, 0) + 1

        rows = [{"name": n, "samples": c,
                 "percent": (100.0 * c / total) if total else 0.0}
                for n, c in counts.items()]
        return sorted(rows, key=lambda r: (-r["samples"], r["name"]))


def detect_spin(samples, threshold=0.9):
    """Is the program stuck?

    Args:
        samples: list of (addr, name) pairs, in time order.
        threshold: fraction of samples at one address that counts as a spin.

    Returns:
        None if execution looks healthy, otherwise a detail string naming the
        address, the function and the fraction.

    An empty sample list is not a spin.
    """
    if not samples:
        return None

    counts = {}
    for addr, name in samples:
        counts[addr] = counts.get(addr, 0) + 1

    addr, count = max(counts.items(), key=lambda kv: (kv[1], -kv[0]))
    fraction = count / len(samples)
    if fraction <= threshold:
        return None

    name = next(n for a, n in samples if a == addr)
    return (f"0x{addr:08X} ({name}) holds {fraction * 100:.1f}% of samples "
            f"-- execution is not advancing")


def format_profile(sampler):
    """Format a profile."""
    rows = sampler.profile()
    total = len(sampler.samples) + sampler.unresolved
    lines = [f"{total} samples ({sampler.unresolved} outside the image)"]
    for r in rows:
        lines.append(f"  {r['percent']:5.1f}%  {r['samples']:6d}  {r['name']}")
    return "\n".join(lines)
