"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 93: Assemble the Address Space

Glue a device's separate images into one address space, and measure what
that alone does to the unresolved-transfer count.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


class Overlap(Exception):
    """Raised when two images would occupy the same addresses."""


class AddressSpace:
    """Several images mapped into one flat space."""

    def __init__(self):
        self.images = []        # list of (base, size, name)

    def add(self, name, base, size):
        """Map an image.

        Raises:
            Overlap: if it would collide with one already mapped. Silently
                allowing an overlap means every later lookup is a coin flip.
        """
        end = base + size
        for other_base, other_size, other_name in self.images:
            if base < other_base + other_size and other_base < end:
                raise Overlap(
                    f"{name} [0x{base:X}, 0x{end:X}) overlaps {other_name}")
        self.images.append((base, size, name))
        self.images.sort()

    def contains(self, addr):
        """Is *addr* inside any mapped image?"""
        return any(base <= addr < base + size for base, size, _ in self.images)

    def image_of(self, addr):
        """Which image owns *addr*?

        Returns:
            The image name, or None.
        """
        for base, size, name in self.images:
            if base <= addr < base + size:
                return name
        return None


def analyse(transfers, space):
    """Classify transfer targets against an address space.

    Args:
        transfers: list of dicts with "site" and "target" addresses.
        space: an AddressSpace.

    Returns:
        A dict with:
            "total"      - how many transfers
            "resolved"   - targets inside the space
            "unresolved" - targets outside it
            "outside"    - sorted list of the unresolved target addresses
    """
    outside = []
    resolved = 0
    for t in transfers:
        if space.contains(t["target"]):
            resolved += 1
        else:
            outside.append(t["target"])
    return {"total": len(transfers), "resolved": resolved,
            "unresolved": len(outside), "outside": sorted(outside)}


def compare_assembly(images, transfers):
    """Compare analysing each image alone against analysing them together.

    Args:
        images: list of (name, base, size) tuples.
        transfers: list of transfer dicts.

    Returns:
        A dict with:
            "separate"   - unresolved count when each image is analysed alone
            "combined"   - unresolved count with everything mapped together
            "recovered"  - separate - combined
            "ratio"      - combined / separate, 0.0 when separate is 0

    Analysing "alone" means: for each image, build a space containing only that
    image, and count the transfers whose *site* is in that image but whose
    target is not.
    """
    combined = AddressSpace()
    for name, base, size in images:
        combined.add(name, base, size)

    separate = 0
    for name, base, size in images:
        solo = AddressSpace()
        solo.add(name, base, size)
        for t in transfers:
            if solo.contains(t["site"]) and not solo.contains(t["target"]):
                separate += 1

    combined_unresolved = analyse(transfers, combined)["unresolved"]
    return {
        "separate": separate,
        "combined": combined_unresolved,
        "recovered": separate - combined_unresolved,
        "ratio": (combined_unresolved / separate) if separate else 0.0,
    }
