"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 119: Verified Lifting Rules

Prove a lifting rule correct over its entire input space, and find what
a sampled differential test missed.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


import itertools
import random


def exhaustive_verify(reference, candidate, width=8, arity=2, flag_states=(False,)):
    """Check *candidate* against *reference* over the entire input space.

    Args:
        reference: known-good callable(*operands, flag) -> result.
        candidate: the implementation under test, same signature.
        width: operand width in bits.
        arity: number of operands.
        flag_states: incoming flag values to try.

    Returns:
        A dict with:
            "verified"   - bool, True only if every input matched
            "checked"    - how many input combinations were tested
            "first_bad"  - the first failing (operands..., flag) tuple, or None
            "expected" / "actual" - values at that input, or None

    Stops at the first failure: once a rule is wrong, it is wrong.
    """
    checked = 0
    for operands in itertools.product(range(1 << width), repeat=arity):
        for flag in flag_states:
            checked += 1
            expected = reference(*operands, flag)
            actual = candidate(*operands, flag)
            if expected != actual:
                return {"verified": False, "checked": checked,
                        "first_bad": operands + (flag,),
                        "expected": expected, "actual": actual}
    return {"verified": True, "checked": checked, "first_bad": None,
            "expected": None, "actual": None}


def sampled_verify(reference, candidate, width=8, arity=2, trials=10000,
                   seed=0, flag_states=(False,)):
    """Check a random sample -- the usual approach.

    Returns:
        The same shape as exhaustive_verify, plus "seed".
    """
    rng = random.Random(seed)
    top = (1 << width) - 1
    flags = list(flag_states)
    for checked in range(1, trials + 1):
        operands = tuple(rng.randint(0, top) for _ in range(arity))
        flag = rng.choice(flags)
        expected = reference(*operands, flag)
        actual = candidate(*operands, flag)
        if expected != actual:
            return {"verified": False, "checked": checked,
                    "first_bad": operands + (flag,), "expected": expected,
                    "actual": actual, "seed": seed}
    return {"verified": True, "checked": trials, "first_bad": None,
            "expected": None, "actual": None, "seed": seed}


def compare_approaches(reference, candidate, width=8, arity=2, trials=10000,
                       seed=0):
    """Run both and report what sampling missed.

    Returns:
        A dict with:
            "exhaustive"  - the exhaustive result
            "sampled"     - the sampled result
            "missed"      - True if sampling passed while exhaustive failed
            "space_size"  - total inputs in the space
            "sampled_fraction" - trials / space_size, capped at 1.0
    """
    full = exhaustive_verify(reference, candidate, width, arity)
    sample = sampled_verify(reference, candidate, width, arity, trials, seed)
    space = (1 << width) ** arity
    return {
        "exhaustive": full,
        "sampled": sample,
        "missed": sample["verified"] and not full["verified"],
        "space_size": space,
        "sampled_fraction": min(1.0, trials / space) if space else 0.0,
    }
