"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 63: Bisect Harness

A LIFT_LO/LIFT_HI style range switch, and a binary search that isolates
one bad function out of thousands.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


def in_range(addr, lo, hi):
    """Is *addr* inside the inclusive range [lo, hi]?

    A range where lo > hi is empty -- nothing is lifted. That is the "all
    original" baseline and must be representable.
    """
    return lo <= addr <= hi


def run_with_range(addrs, lo, hi, oracle_fn, lifted_fn):
    """Execute each address with the lifted or the original implementation.

    Args:
        addrs: list of addresses, in execution order.
        lo, hi: inclusive range of addresses to run lifted.
        oracle_fn: callable(addr) -> value, the known-good implementation.
        lifted_fn: callable(addr) -> value, the implementation under test.

    Returns:
        A list of the values produced, in order.
    """
    return [lifted_fn(a) if in_range(a, lo, hi) else oracle_fn(a) for a in addrs]


def bisect(addrs, test):
    """Find the lowest address whose inclusion in the lifted range fails *test*.

    `test(lo, hi)` returns True when running [lo, hi] lifted is GOOD.

    The search assumes monotonicity: if lifting up to address X is bad, lifting
    up to anything beyond X is also bad. That holds when exactly one function is
    broken, which is the case this technique is for.

    Args:
        addrs: sorted list of candidate addresses.
        test: callable(lo, hi) -> bool.

    Returns:
        The offending address, or None if test(all) is already good.
    """
    found, _log = bisect_log(addrs, test)
    return found


def bisect_log(addrs, test):
    """Like bisect(), but also return every range tried.

    Returns:
        A tuple (found_addr_or_None, log), where log is a list of dicts with
        "lo", "hi" and "good".
    """
    log = []

    def probe(lo, hi):
        good = test(lo, hi)
        log.append({"lo": lo, "hi": hi, "good": good})
        return good

    if not addrs or probe(addrs[0], addrs[-1]):
        return None, log

    # Smallest prefix [addrs[0], addrs[i]] that is bad.
    lo_i, hi_i = 0, len(addrs) - 1
    while lo_i < hi_i:
        mid = (lo_i + hi_i) // 2
        if probe(addrs[0], addrs[mid]):
            lo_i = mid + 1
        else:
            hi_i = mid

    return addrs[lo_i], log


def format_log(found, log):
    """Format a bisection log."""
    lines = [f"bisection: {len(log)} run(s)"]
    for entry in log:
        tag = "good" if entry["good"] else "BAD "
        lines.append(f"  [0x{entry['lo']:X}, 0x{entry['hi']:X}] {tag}")
    lines.append(f"  => {'0x%X' % found if found is not None else 'no bad function'}")
    return "\n".join(lines)
