"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 40: Shader Translator Prototype

Translate a JSON combiner description into a GLSL fragment shader.
"""

import json


# ---------------------------------------------------------------------------
# Alpha-test comparison operators mapped to GLSL
# ---------------------------------------------------------------------------

ALPHA_FUNC_GLSL = {
    "greater": ">",
    "less":    "<",
    "gequal":  ">=",
    "lequal":  "<=",
    "equal":   "==",
    "never":   None,   # always discard
    "always":  None,   # never discard (no-op)
}


# ---------------------------------------------------------------------------
# Code-generation helpers -- complete the TODOs
# ---------------------------------------------------------------------------

def emit_version():
    """Return the GLSL version directive.

    Returns
    -------
    str
        '#version 330 core'
    """
    return "#version 330 core"


def emit_texture_uniforms(texture_indices):
    """Emit uniform sampler2D declarations for each texture index.

    Parameters
    ----------
    texture_indices : list of int
        e.g. [0, 1] -> two uniform declarations.

    Returns
    -------
    list of str
        Each string is one line, e.g. 'uniform sampler2D u_tex0;'
    """
    return [f"uniform sampler2D u_tex{i};" for i in texture_indices]


def emit_texture_samples(texture_indices):
    """Emit texture sampling statements.

    Each texture is sampled into a local variable named t<N>.

    Returns
    -------
    list of str
        e.g. ['    vec4 t0 = texture(u_tex0, v_texcoord);']
    """
    return [
        f"    vec4 t{i} = texture(u_tex{i}, v_texcoord);"
        for i in texture_indices
    ]


def emit_combine(texture_indices, color_mode):
    """Emit the color combine statement.

    Parameters
    ----------
    texture_indices : list of int
    color_mode : str
        One of 'replace', 'modulate', 'add', 'decal'.

    Returns
    -------
    str
        An indented C statement like '    vec4 combined = t0 * t1;'

    Behavior by mode:
        replace  -> combined = t0
        modulate -> combined = t0 * t1 (* t2 * ... if more textures)
        add      -> combined = clamp(t0 + t1 (+ t2 ...), 0.0, 1.0)
        decal    -> combined = mix(t1, t0, t0.a)
                    (blend t0 onto t1 using t0's alpha; needs >= 2 textures,
                     if only 1 texture, fall back to replace)
    """
    names = [f"t{i}" for i in texture_indices]

    if not names:
        return "    vec4 combined = vec4(1.0);"

    if color_mode == "replace" or len(names) == 1:
        if color_mode == "add" and len(names) == 1:
            return f"    vec4 combined = clamp({names[0]}, 0.0, 1.0);"
        return f"    vec4 combined = {names[0]};"

    if color_mode == "modulate":
        return "    vec4 combined = " + " * ".join(names) + ";"

    if color_mode == "add":
        return "    vec4 combined = clamp(" + " + ".join(names) + ", 0.0, 1.0);"

    if color_mode == "decal":
        # Blend the first texture over the second using its own alpha.
        return f"    vec4 combined = mix({names[1]}, {names[0]}, {names[0]}.a);"

    raise ValueError(f"Unknown color mode: {color_mode}")


def emit_alpha_test(alpha_test):
    """Emit an alpha test discard statement.

    Parameters
    ----------
    alpha_test : dict or None
        {"func": "greater", "ref": 0.5} or None.

    Returns
    -------
    str or None
        An indented discard statement, or None if no alpha test.

    For func == "never":  always discard -> '    discard;'
    For func == "always": no test needed -> return None
    For comparison funcs: '    if (!(combined.a > 0.5)) discard;'
    """
    if not alpha_test:
        return None

    func = alpha_test["func"]
    if func == "never":
        return "    discard;"
    if func == "always":
        return None

    op = ALPHA_FUNC_GLSL.get(func)
    if op is None:
        raise ValueError(f"Unknown alpha test function: {func}")

    ref = alpha_test["ref"]
    return f"    if (!(combined.a {op} {ref})) discard;"


def translate(combiner):
    """Translate a combiner description dict into a GLSL fragment shader.

    Parameters
    ----------
    combiner : dict
        {
            "textures": [0, 1],
            "color_mode": "modulate",
            "alpha_test": {"func": "greater", "ref": 0.5}  // optional
        }

    Returns
    -------
    str
        Complete GLSL fragment shader source.
    """
    textures = combiner.get("textures", [])
    lines = [emit_version(), "", "in vec2 v_texcoord;"]
    lines.extend(emit_texture_uniforms(textures))
    lines.append("out vec4 frag_color;")
    lines.append("")
    lines.append("void main() {")
    lines.extend(emit_texture_samples(textures))
    lines.append(emit_combine(textures, combiner.get("color_mode", "replace")))

    alpha = emit_alpha_test(combiner.get("alpha_test"))
    if alpha is not None:
        lines.append(alpha)

    lines.append("    frag_color = combined;")
    lines.append("}")
    return "\n".join(lines)


def translate_json(json_str):
    """Convenience: parse a JSON string and translate it.

    Parameters
    ----------
    json_str : str
        JSON-encoded combiner description.

    Returns
    -------
    str
        GLSL fragment shader source.
    """
    return translate(json.loads(json_str))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    sample = {
        "textures": [0, 1],
        "color_mode": "modulate",
        "alpha_test": {"func": "greater", "ref": 0.5},
    }
    print(translate(sample))
