"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 29: Project Plan Checklist Validator

Parses a Markdown project plan and verifies that all required sections
are present and contain real content (not just the TODO placeholder).
"""

import sys
import os
import re

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


# ---------------------------------------------------------------------------
# Required sections
# ---------------------------------------------------------------------------

REQUIRED_SECTIONS = [
    "Target Binary",
    "Architecture",
    "Tool Selection",
    "Milestones",
    "Risk Assessment",
    "Success Criteria",
]

# Sections that need numbered/bulleted items
SECTIONS_WITH_ITEMS = {
    "Milestones": 3,       # at least 3 milestones
    "Risk Assessment": 2,  # at least 2 risks
}


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def parse_sections(text):
    """Parse a Markdown document into sections.

    Args:
        text: the full Markdown text.

    Returns:
        A dict mapping section title (str) -> section body (str).
        Section titles are taken from ## headings, stripped of
        leading/trailing whitespace.
    """
    sections = {}
    title = None
    body = []
    for line in text.splitlines():
        if line.startswith("## "):
            if title is not None:
                sections[title] = "\n".join(body)
            title = line[3:].strip()
            body = []
        elif title is not None:
            body.append(line)
    if title is not None:
        sections[title] = "\n".join(body)
    return sections


def check_section_present(sections, title):
    """Check whether a section exists and has content beyond the TODO placeholder.

    Args:
        sections: dict from parse_sections().
        title: the section title to look for.

    Returns:
        Tuple of (found, has_content):
            found: bool, True if the section heading exists.
            has_content: bool, True if the body contains text other
                         than the [TODO: ...] placeholder.
    """
    if title not in sections:
        return False, False
    # Strip the [TODO: ...] placeholders and see whether anything real is left.
    remainder = re.sub(r"\[TODO:.*?\]", "", sections[title], flags=re.S)
    return True, bool(remainder.strip())


def count_list_items(sections, title):
    """Count numbered or bulleted list items in a section.

    Looks for lines starting with "- " or "N. " (where N is a digit).

    Args:
        sections: dict from parse_sections().
        title: the section title.

    Returns:
        The number of list items found (int). Returns 0 if section
        is missing.
    """
    body = sections.get(title)
    if not body:
        return 0
    return sum(
        1 for line in body.splitlines()
        if re.match(r"^\s*(\d+\.|[-*])\s", line)
    )


def run_checklist(filepath):
    """Run the full checklist against a project plan file.

    Args:
        filepath: path to the Markdown file.

    Returns:
        Tuple of (passed, failed) where each is a list of message strings.
    """
    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read()

    sections = parse_sections(text)
    if sections is None:
        return [], ["parse_sections() returned None"]

    passed = []
    failed = []

    for title in REQUIRED_SECTIONS:
        found, has_content = check_section_present(sections, title)
        if not found:
            failed.append(f"Section missing: {title}")
        elif not has_content:
            failed.append(f"Section not filled in: {title}")
        else:
            if title in SECTIONS_WITH_ITEMS:
                min_items = SECTIONS_WITH_ITEMS[title]
                count = count_list_items(sections, title)
                if count >= min_items:
                    passed.append(
                        f"Section found: {title} ({count} items found)")
                else:
                    failed.append(
                        f"Section {title}: need {min_items} items, "
                        f"found {count}")
            else:
                passed.append(f"Section found: {title}")

    return passed, failed


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <project_plan.md>")
        sys.exit(1)

    filepath = sys.argv[1]
    if not os.path.isfile(filepath):
        print(f"Error: file not found: {filepath}")
        sys.exit(1)

    print(f"Checking {filepath}...")
    passed, failed = run_checklist(filepath)

    for msg in passed:
        print(f"[PASS] {msg}")
    for msg in failed:
        print(f"[FAIL] {msg}")

    print()
    if not failed:
        print("All checks passed! Your project plan is complete.")
    else:
        print(f"{len(failed)} check(s) failed. Fill in the missing sections.")
        sys.exit(1)


if __name__ == "__main__":
    main()
