"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 42: SPU Task Scheduler

Simulate the PS3 Cell's SPE task scheduling.  The scheduler manages 6 SPE
contexts and a priority queue of tasks.
"""


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

NUM_SPES = 6


# ---------------------------------------------------------------------------
# Task class
# ---------------------------------------------------------------------------

class SpuTask:
    """Represents a task to be run on an SPE.

    Attributes
    ----------
    task_id : int
        Unique identifier.
    program : str
        Name of the SPE program (simulated).
    priority : int
        Scheduling priority (0 = highest).
    dma_transfers : list of int
        Sizes of DMA transfers the task will perform.
    status : str
        One of 'pending', 'running', 'waiting_dma', 'completed'.
    assigned_spe : int or None
        Which SPE (0-5) this task is assigned to, or None.
    """

    def __init__(self, task_id, program, priority=0, dma_transfers=None):
        self.task_id = task_id
        self.program = program
        self.priority = priority
        self.dma_transfers = dma_transfers or []
        self.status = "pending"
        self.assigned_spe = None

    def __repr__(self):
        return (f"SpuTask(id={self.task_id}, prog='{self.program}', "
                f"pri={self.priority}, status='{self.status}', "
                f"spe={self.assigned_spe})")


# ---------------------------------------------------------------------------
# Scheduler
# ---------------------------------------------------------------------------

class SpuScheduler:
    """Simple priority-based SPE task scheduler.

    Attributes
    ----------
    spe_slots : list
        Length-6 list; each entry is either None (free) or an SpuTask.
    pending_queue : list of SpuTask
        Tasks waiting to be dispatched.
    completed : list of SpuTask
        Tasks that have finished.
    """

    def __init__(self):
        self.spe_slots = [None] * NUM_SPES
        self.pending_queue = []
        self.completed = []

    def submit(self, task):
        """Submit a task to the scheduler.

        The task is added to the pending queue.  The scheduler should then
        attempt to dispatch it (call _try_dispatch).

        Parameters
        ----------
        task : SpuTask
        """
        task.status = "pending"
        self.pending_queue.append(task)
        self._try_dispatch()

    def _try_dispatch(self):
        """Try to dispatch pending tasks to free SPE slots.

        Sort the pending queue by (priority, task_id) so that:
        - Lower priority number goes first.
        - Among equal priorities, lower task_id (earlier submission) goes first.

        For each free SPE slot, pop the highest-priority pending task and
        assign it.
        """
        # Lower priority number wins; ties broken by submission order (task_id).
        self.pending_queue.sort(key=lambda t: (t.priority, t.task_id))
        for slot in range(len(self.spe_slots)):
            if self.spe_slots[slot] is not None:
                continue
            if not self.pending_queue:
                break
            task = self.pending_queue.pop(0)
            task.assigned_spe = slot
            task.status = "running"
            self.spe_slots[slot] = task

    def get_free_spe_count(self):
        """Return the number of free (unoccupied) SPE slots.

        Returns
        -------
        int
        """
        return sum(1 for slot in self.spe_slots if slot is None)

    def get_running_tasks(self):
        """Return a list of tasks currently assigned to SPEs.

        Returns
        -------
        list of SpuTask
        """
        return [slot for slot in self.spe_slots if slot is not None]

    def start_dma(self, task_id):
        """Transition a running task to 'waiting_dma' status.

        Parameters
        ----------
        task_id : int

        Raises
        ------
        ValueError
            If the task is not in 'running' status.
        """
        for task in self.spe_slots:
            if task is not None and task.task_id == task_id:
                if task.status != "running":
                    raise ValueError(
                        f"Task {task_id} is '{task.status}', expected 'running'"
                    )
                task.status = "waiting_dma"
                return
        raise ValueError(f"Task {task_id} is not assigned to an SPE")

    def complete_dma(self, task_id):
        """Complete DMA for a task, marking it done and freeing the SPE.

        Parameters
        ----------
        task_id : int

        Raises
        ------
        ValueError
            If the task is not in 'waiting_dma' status.

        After completing:
        1. Set task status to "completed".
        2. Clear task.assigned_spe.
        3. Remove it from spe_slots (set slot to None).
        4. Append it to self.completed.
        5. Call _try_dispatch() to schedule pending tasks.
        """
        for slot, task in enumerate(self.spe_slots):
            if task is not None and task.task_id == task_id:
                if task.status != "waiting_dma":
                    raise ValueError(
                        f"Task {task_id} is '{task.status}', expected 'waiting_dma'"
                    )
                task.status = "completed"
                task.assigned_spe = None
                self.spe_slots[slot] = None
                self.completed.append(task)
                self._try_dispatch()
                return
        raise ValueError(f"Task {task_id} is not assigned to an SPE")

    def complete_task(self, task_id):
        """Directly complete a running task (no DMA phase).

        Same as complete_dma but for tasks in 'running' status.
        """
        for slot, task in enumerate(self.spe_slots):
            if task is not None and task.task_id == task_id:
                if task.status != "running":
                    raise ValueError(
                        f"Task {task_id} is '{task.status}', expected 'running'"
                    )
                task.status = "completed"
                task.assigned_spe = None
                self.spe_slots[slot] = None
                self.completed.append(task)
                self._try_dispatch()
                return
        raise ValueError(f"Task {task_id} is not assigned to an SPE")

    def get_task_status(self, task_id):
        """Look up a task by ID and return its status string.

        Searches pending queue, SPE slots, and completed list.

        Returns
        -------
        str or None
            The task's status, or None if not found.
        """
        for task in self.pending_queue:
            if task.task_id == task_id:
                return task.status
        for task in self.spe_slots:
            if task is not None and task.task_id == task_id:
                return task.status
        for task in self.completed:
            if task.task_id == task_id:
                return task.status
        return None

    def get_completed_tasks(self):
        """Return the list of completed tasks.

        Returns
        -------
        list of SpuTask
        """
        return self.completed


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    sched = SpuScheduler()

    for i in range(8):
        t = SpuTask(task_id=i, program=f"prog_{i}", priority=i % 3,
                    dma_transfers=[64, 128])
        sched.submit(t)

    print(f"Free SPEs: {sched.get_free_spe_count()}")
    print(f"Running: {sched.get_running_tasks()}")
    print(f"Pending: {len(sched.pending_queue)} tasks")

    # Complete first two tasks
    sched.start_dma(0)
    sched.complete_dma(0)
    sched.complete_task(1)

    print(f"\nAfter completions:")
    print(f"Free SPEs: {sched.get_free_spe_count()}")
    print(f"Running: {sched.get_running_tasks()}")
    print(f"Completed: {sched.get_completed_tasks()}")
