"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 76: Memory Access Ladder

Three rungs of guest memory access -- a switch, a flat array, and a based
pointer -- measured on the same workload.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


class IOTrap(Exception):
    """Raised when a bus implementation loses a memory-mapped access."""


class SwitchBus:
    """Rung 0: a chain of range comparisons, one per access.

    Attributes:
        comparisons: how many range checks were performed. This is the cost
            being measured.
    """

    def __init__(self, regions, io_handler=None):
        # regions: list of (start, size, bytearray) in check order
        self.regions = regions
        self.io_handler = io_handler
        self.comparisons = 0

    def read(self, addr):
        """Read one byte, walking the region list in order.

        Increments self.comparisons once per region examined, including the
        one that matches.

        Returns:
            The byte value.

        Raises:
            IOTrap: if no region matches and there is no io_handler.
        """
        for start, size, data in self.regions:
            self.comparisons += 1
            if start <= addr < start + size:
                return data[addr - start]

        if self.io_handler is not None:
            return self.io_handler(addr)
        raise IOTrap(f"unmapped address 0x{addr:X}")


class FlatBus:
    """Rung 1: one array plus a base offset, with an I/O window check.

    Attributes:
        checks: how many I/O window comparisons were performed -- one per
            access, which is the entire per-access cost.
    """

    def __init__(self, size, base, io_range=None, io_handler=None):
        self.memory = bytearray(size)
        self.base = base
        self.io_range = io_range        # (lo, hi) inclusive, or None
        self.io_handler = io_handler
        self.checks = 0

    def read(self, addr):
        """Read one byte by offset arithmetic, after one I/O window check.

        Returns:
            The byte value.

        Raises:
            IOTrap: if the address is in the I/O window and no handler is set.
                Silently returning RAM for a hardware register is the exact
                failure Module 43 section 2 warns about.
        """
        self.checks += 1

        if self.io_range is not None and self.io_range[0] <= addr <= self.io_range[1]:
            if self.io_handler is not None:
                return self.io_handler(addr)
            # Returning RAM here would silently turn a hardware register into a
            # stale byte -- the exact failure Module 43 section 2 warns about.
            raise IOTrap(f"memory-mapped access at 0x{addr:X} with no handler")

        return self.memory[addr - self.base]


def classify_static(addr, io_range):
    """Decide at lift time whether an access needs the slow path.

    Most guest addresses are compile-time constants, so the lifter can emit the
    fast path directly and skip the runtime check entirely.

    Args:
        addr: the constant address, or None if it is computed at runtime.
        io_range: (lo, hi) inclusive, or None.

    Returns:
        "fast"    - a constant address outside the I/O window
        "io"      - a constant address inside it
        "dynamic" - not known at lift time, needs the runtime check
    """
    if addr is None:
        return "dynamic"
    if io_range is not None and io_range[0] <= addr <= io_range[1]:
        return "io"
    return "fast"


def benchmark(bus, accesses):
    """Run a list of addresses through a bus and report its work.

    Returns:
        A dict with "accesses", "work" (the bus's own counter) and
        "work_per_access".
    """
    for addr in accesses:
        bus.read(addr)

    work = getattr(bus, "comparisons", None)
    if work is None:
        work = getattr(bus, "checks", 0)

    count = len(accesses)
    return {"accesses": count, "work": work,
            "work_per_access": (work / count) if count else 0.0}
