"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 55: Synthetic Fixture Suite

Hand-assembled instruction fixtures and golden-output assertions -- the
highest-value test a recompiler can have, and legally free of the ROM.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


import difflib

# A tiny assembler vocabulary: mnemonic -> (opcode, operand_bytes)
OPCODES = {
    "nop":   (0x00, 0),
    "ld_a":  (0x3E, 1),
    "add_a": (0x87, 0),
    "jp":    (0xC3, 2),
    "jp_nz": (0xC2, 2),
    "call":  (0xCD, 2),
    "ret":   (0xC9, 0),
    "jp_hl": (0xE9, 0),
}


class Fixture:
    """A named test case: source, assembled bytes, and expected lifter output.

    Attributes:
        name: what this fixture is testing.
        source: list of assembly lines.
        expected: the golden lifter output, or None if not yet recorded.
        why: one line saying why this case is hard. Fixtures without a
             reason tend to be the easy cases nobody needed tested.
    """

    def __init__(self, name, source, expected=None, why=""):
        self.name = name
        self.source = source
        self.expected = expected
        self.why = why


def assemble(lines):
    """Assemble a list of source lines into bytes.

    Each line is a mnemonic optionally followed by a hex operand:

        nop
        ld_a 0x42
        jp 0x1234

    Blank lines and lines starting with ";" are ignored. A 1-byte operand is
    emitted as-is; a 2-byte operand is little-endian.

    Args:
        lines: list of strings.

    Returns:
        A bytes object.

    Raises:
        ValueError: on an unknown mnemonic, or a missing or extra operand.
    """
    out = bytearray()
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith(";"):
            continue

        parts = line.split()
        mnemonic = parts[0]
        if mnemonic not in OPCODES:
            raise ValueError(f"unknown mnemonic {mnemonic!r}")

        opcode, nbytes = OPCODES[mnemonic]
        operands = parts[1:]
        if nbytes == 0 and operands:
            raise ValueError(f"{mnemonic} takes no operand")
        if nbytes > 0 and not operands:
            raise ValueError(f"{mnemonic} needs an operand")

        out.append(opcode)
        if nbytes:
            value = int(operands[0], 0)
            for shift in range(nbytes):
                out.append((value >> (8 * shift)) & 0xFF)

    return bytes(out)


def run_fixture(fixture, lifter):
    """Run one fixture through *lifter* and compare against its golden text.

    Args:
        fixture: a Fixture.
        lifter: callable(bytes) -> str, the lifter under test.

    Returns:
        A dict with keys:
            "name"     - the fixture name
            "status"   - "pass", "fail", or "no_golden"
            "actual"   - the lifter's output
            "diff"     - unified diff text when status is "fail", else ""

    A fixture with expected=None is "no_golden" -- not a pass. An unrecorded
    golden is an untested fixture, and counting it as a pass is how a suite
    quietly stops testing anything.
    """
    actual = lifter(assemble(fixture.source))

    if fixture.expected is None:
        # Not a pass. An unrecorded golden is an untested fixture.
        return {"name": fixture.name, "status": "no_golden",
                "actual": actual, "diff": ""}

    if actual == fixture.expected:
        return {"name": fixture.name, "status": "pass",
                "actual": actual, "diff": ""}

    diff = "\n".join(difflib.unified_diff(
        fixture.expected.splitlines(), actual.splitlines(),
        fromfile="golden", tofile="actual", lineterm=""))
    return {"name": fixture.name, "status": "fail", "actual": actual, "diff": diff}


def run_suite(fixtures, lifter):
    """Run every fixture and summarise.

    Returns:
        A dict with keys:
            "results"   - list of run_fixture dicts, in input order
            "passed"    - int
            "failed"    - int
            "no_golden" - int
    """
    results = [run_fixture(f, lifter) for f in fixtures]
    return {
        "results": results,
        "passed": sum(1 for r in results if r["status"] == "pass"),
        "failed": sum(1 for r in results if r["status"] == "fail"),
        "no_golden": sum(1 for r in results if r["status"] == "no_golden"),
    }


def regenerate(fixtures, lifter):
    """Produce updated golden text for every fixture.

    This deliberately does NOT modify the fixtures in place. It returns the
    new goldens so a human can review the diff before committing them.

    Returns:
        A dict mapping fixture name -> new golden text.
    """
    # Deliberately returns the new goldens rather than writing them back:
    # a human reads the diff before any of this is committed.
    return {f.name: lifter(assemble(f.source)) for f in fixtures}


def format_report(summary):
    """Format a suite summary, with diffs for failures."""
    lines = [f"fixtures: {len(summary['results'])}  "
             f"passed: {summary['passed']}  "
             f"failed: {summary['failed']}  "
             f"no golden: {summary['no_golden']}"]
    for r in summary["results"]:
        if r["status"] == "fail":
            lines.append(f"\nFAIL {r['name']}")
            lines.append(r["diff"])
        elif r["status"] == "no_golden":
            lines.append(f"\nNO GOLDEN {r['name']} -- record it or delete it")
    return "\n".join(lines)
