"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 2: PE Explorer

Parse and display the structure of a Portable Executable (PE) file
using the pefile library.
"""

import sys
import os

try:
    import pefile
except ImportError:
    print("Error: the 'pefile' package is required. Install it with:")
    print("  pip install pefile")
    sys.exit(1)


# ---------------------------------------------------------------------------
# Section Parsing
# ---------------------------------------------------------------------------

def dump_sections(pe):
    """Print information about each section in the PE file.

    For each section, display:
      - Name (decoded, stripped of null bytes)
      - Virtual Address
      - Virtual Size
      - Characteristics flags

    Args:
        pe: A loaded pefile.PE object.
    """
    print("--- Sections ---")
    for section in pe.sections:
        name = section.Name.decode("utf-8", errors="replace").rstrip("\x00")
        va = section.VirtualAddress
        size = section.Misc_VirtualSize
        flags = section.Characteristics
        print(f"  {name:<10s} VA: 0x{va:08x}  Size: 0x{size:08x}  Flags: 0x{flags:08x}")
    print()


# ---------------------------------------------------------------------------
# Import Parsing
# ---------------------------------------------------------------------------

def dump_imports(pe):
    """Print the import directory: each DLL and its imported functions.

    Args:
        pe: A loaded pefile.PE object.
    """
    print("--- Imports ---")
    if not hasattr(pe, "DIRECTORY_ENTRY_IMPORT"):
        print("  (no imports)")
        print()
        return

    for entry in pe.DIRECTORY_ENTRY_IMPORT:
        dll_name = entry.dll.decode("utf-8", errors="replace")
        print(f"  {dll_name}")
        for imp in entry.imports:
            if imp.name:
                func_name = imp.name.decode("utf-8", errors="replace")
                print(f"    {func_name}")
            else:
                print(f"    ordinal {imp.ordinal}")
    print()


# ---------------------------------------------------------------------------
# Export Parsing
# ---------------------------------------------------------------------------

def dump_exports(pe):
    """Print the export directory: each exported function name and ordinal.

    Args:
        pe: A loaded pefile.PE object.
    """
    print("--- Exports ---")
    if not hasattr(pe, "DIRECTORY_ENTRY_EXPORT"):
        print("  (no exports)")
    else:
        for symbol in pe.DIRECTORY_ENTRY_EXPORT.symbols:
            if symbol.name:
                name = symbol.name.decode("utf-8", errors="replace")
            else:
                name = "(unnamed)"
            print(f"  {symbol.ordinal:<6d} {name}")
    print()


# ---------------------------------------------------------------------------
# Resource Parsing
# ---------------------------------------------------------------------------

def dump_resources(pe, indent=0):
    """Print the resource directory tree.

    Args:
        pe: A loaded pefile.PE object.
        indent: Current indentation level (for recursive display).
    """
    print("--- Resources ---")
    if not hasattr(pe, "DIRECTORY_ENTRY_RESOURCE"):
        print("  (no resources)")
    else:
        def walk(entries, depth):
            pad = "  " * (depth + 1)
            for entry in entries:
                label = entry.name if entry.name is not None else f"ID {entry.id}"
                print(f"{pad}{label}")
                if hasattr(entry, "directory"):
                    walk(entry.directory.entries, depth + 1)
                elif hasattr(entry, "data"):
                    print(f"{pad}  ({entry.data.struct.Size} bytes)")

        walk(pe.DIRECTORY_ENTRY_RESOURCE.entries, indent)
    print()


# ---------------------------------------------------------------------------
# Main Display
# ---------------------------------------------------------------------------

def analyze_pe(filepath):
    """Load a PE file and display its structure.

    Args:
        filepath: Path to the PE file.
    """
    pe = pefile.PE(filepath)

    filename = os.path.basename(filepath)
    print(f"=== PE File: {filename} ===")
    print(f"Entry Point:   0x{pe.OPTIONAL_HEADER.AddressOfEntryPoint:08x}")
    print(f"Image Base:    0x{pe.OPTIONAL_HEADER.ImageBase:08x}")
    print()

    dump_sections(pe)
    dump_imports(pe)
    dump_exports(pe)
    dump_resources(pe)

    pe.close()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <file.exe|file.dll>")
        sys.exit(1)

    filepath = sys.argv[1]
    if not os.path.isfile(filepath):
        print(f"Error: file not found: {filepath}")
        sys.exit(1)

    analyze_pe(filepath)


if __name__ == "__main__":
    main()
