"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 75: Lane Order and Permutes

Lift a big-endian guest's permute to a little-endian host correctly, and
demonstrate the mirrored-constant bug the naive translation produces.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


def mirror_index(i, count):
    """Convert a lane index between big-endian and little-endian ordering.

    With `count` lanes, lane 0 at one end corresponds to lane `count - 1` at
    the other. The conversion is its own inverse.

    Raises:
        ValueError: if i is outside [0, count).
    """
    if not 0 <= i < count:
        raise ValueError(f"lane {i} outside [0, {count})")
    return count - 1 - i


def permute(vec, control):
    """Apply a permute control vector.

    Args:
        vec: the source lanes.
        control: list of source indices, one per destination lane.

    Returns:
        A new list where result[i] = vec[control[i]].

    Raises:
        IndexError: if any control entry is out of range.
    """
    out = []
    for src in control:
        if not 0 <= src < len(vec):
            raise IndexError(f"control index {src} outside [0, {len(vec)})")
        out.append(vec[src])
    return out


def lift_permute_naive(control):
    """The WRONG translation: copy the guest's control vector unchanged.

    This is what a lifter does when nobody thought about lane order. It is
    correct only when the guest and host agree on lane numbering.

    Returns:
        The control vector, unchanged.
    """
    return list(control)


def lift_permute(control, count):
    """The correct translation for a big-endian guest on a little-endian host.

    Both the *position* of each control entry and the *value* it selects are
    expressed in guest lane numbering, so both must be mirrored.

    Args:
        control: the guest's control vector.
        count: the number of lanes.

    Returns:
        A control vector in host lane numbering.
    """
    # Both the destination position and the selected source are expressed in
    # guest lane numbering, so both have to be mirrored.
    out = []
    for host_dst in range(count):
        guest_dst = mirror_index(host_dst, count)
        guest_src = control[guest_dst]
        out.append(mirror_index(guest_src, count))
    return out


def demonstrate_bug(vec, control):
    """Run both translations and report whether they differ.

    Returns:
        A dict with:
            "naive"   - result of permuting with the naive control
            "correct" - result of permuting with the corrected control
            "differ"  - bool
    """
    count = len(vec)
    naive = permute(vec, lift_permute_naive(control))
    correct = permute(vec, lift_permute(control, count))
    return {"naive": naive, "correct": correct, "differ": naive != correct}
