"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 58: Variant Build

Drive two revisions of the same game from two manifests sharing one
runtime, and report the address deltas between them.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


from collections import Counter


class Variant:
    """One revision of a game.

    Attributes:
        name: revision name, e.g. "rev-a".
        functions: dict mapping function name -> address.
        hints: list of dicts with "addr" and "source" (from Lab 57).
    """

    def __init__(self, name, functions, hints=None):
        self.name = name
        self.functions = functions
        self.hints = hints or []


def load_variants(specs):
    """Build Variant objects from a list of specs.

    Args:
        specs: list of dicts with "name", "functions" and optional "hints".

    Returns:
        A list of Variant objects, in input order.

    Raises:
        ValueError: on a duplicate variant name. Two variants with the same
            name means one silently shadows the other in every report.
    """
    out = []
    seen = set()
    for spec in specs:
        name = spec["name"]
        if name in seen:
            raise ValueError(f"duplicate variant name {name!r}")
        seen.add(name)
        out.append(Variant(name, spec["functions"], spec.get("hints")))
    return out


def common_functions(a, b):
    """Return the function names present in both variants.

    Returns:
        A sorted list of names.
    """
    return sorted(set(a.functions) & set(b.functions))


def compute_deltas(a, b):
    """Compute the address shift for every function present in both.

    The shift for a function is (address in b) - (address in a). It may be
    negative if code was removed.

    Returns:
        A dict mapping function name -> shift (int), for common functions only.
    """
    return {
        name: b.functions[name] - a.functions[name]
        for name in common_functions(a, b)
    }


def dominant_shift(deltas):
    """Find the most common shift and how much of the binary it explains.

    Returns:
        A dict with keys:
            "shift"    - the most common delta (int), or None if deltas is empty
            "count"    - how many functions have that shift
            "total"    - how many functions were compared
            "coverage" - count / total as a float, 0.0 when total is 0

    When two shifts tie, prefer the one with the smaller absolute value: a
    small shift is the more likely explanation for a revision, and an
    arbitrary tie-break makes the report unstable between runs.
    """
    total = len(deltas)
    if total == 0:
        return {"shift": None, "count": 0, "total": 0, "coverage": 0.0}

    counts = Counter(deltas.values())
    # Most common wins; ties go to the smaller magnitude, so the report is
    # stable between runs and prefers the likelier explanation.
    shift, count = max(counts.items(), key=lambda kv: (kv[1], -abs(kv[0])))
    return {"shift": shift, "count": count, "total": total,
            "coverage": count / total}


def port_hints(hints, shift):
    """Carry hints from one revision to another by applying *shift*.

    Each ported hint keeps its original note but records that it was ported,
    because a ported hint is a *guess* until something confirms it -- exactly
    the distinction Module 14 says decides a bring-up.

    Args:
        hints: list of dicts with "addr" and "source".
        shift: int to add to each address.

    Returns:
        A new list of dicts with the shifted "addr" and a "source" of
        "ported +0xNN from <original source>" (or "-0xNN" when negative).
        The input is not modified.
    """
    sign = "+" if shift >= 0 else "-"
    label = f"{sign}0x{abs(shift):X}"
    return [
        {"addr": h["addr"] + shift,
         "source": f"ported {label} from {h['source']}"}
        for h in hints
    ]


def format_delta_report(a, b, deltas, dominant):
    """Format a comparison between two variants."""
    lines = [
        f"=== {a.name} -> {b.name} ===",
        f"  functions in {a.name}: {len(a.functions)}",
        f"  functions in {b.name}: {len(b.functions)}",
        f"  common:               {len(deltas)}",
    ]
    if dominant["shift"] is None:
        lines.append("  no common functions -- these revisions share nothing")
        return "\n".join(lines)

    sign = "+" if dominant["shift"] >= 0 else "-"
    lines.append(f"  dominant shift:       {sign}0x{abs(dominant['shift']):X} "
                 f"({dominant['count']}/{dominant['total']}, "
                 f"{dominant['coverage'] * 100:.1f}%)")
    if dominant["coverage"] < 0.5:
        lines.append("  NOTE: low coverage -- these revisions genuinely diverge,")
        lines.append("        so porting hints is per-function work.")
    return "\n".join(lines)
