"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 103: Symbol Importer

Convert a decompilation project's symbols into your function-set file,
record which upstream commit they came from, and report what changed.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


def parse_symbols(text):
    """Parse an upstream symbol file.

    Format, one symbol per line:

        80056780 Player_Init 0x120
        80056900 Player_Update 0x80

    Fields are whitespace-separated: hex address, name, hex size. Blank lines
    and lines starting with "#" are ignored.

    Returns:
        A list of dicts with "addr", "name" and "size", in file order.

    Raises:
        ValueError: on a malformed line. A symbol file you half-parsed is
            worse than one you rejected.
    """
    symbols = []
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split()
        if len(fields) != 3:
            raise ValueError(
                f"line {lineno}: expected 3 fields, got {len(fields)}: {line!r}")
        addr, name, size = fields
        try:
            symbols.append({"addr": int(addr, 16), "name": name,
                            "size": int(size, 16)})
        except ValueError:
            raise ValueError(f"line {lineno}: bad hex in {line!r}")
    return symbols


def validate_symbols(symbols):
    """Check imported symbols before trusting them.

    Returns:
        A list of problem strings. Empty means they look sane.

    Checks:
      - zero or negative size
      - duplicate addresses
      - overlapping extents (sorted by address, each must end at or before the
        next one starts)
    """
    problems = []
    seen = {}
    for sym in symbols:
        if sym["size"] <= 0:
            problems.append(f"{sym['name']}: size is {sym['size']}")
        if sym["addr"] in seen:
            problems.append(
                f"{sym['name']}: duplicate address 0x{sym['addr']:X} "
                f"(also {seen[sym['addr']]})")
        else:
            seen[sym["addr"]] = sym["name"]

    ordered = sorted(symbols, key=lambda s: s["addr"])
    for prev, cur in zip(ordered, ordered[1:]):
        end = prev["addr"] + prev["size"]
        if end > cur["addr"]:
            problems.append(
                f"{prev['name']} overlaps {cur['name']}: ends 0x{end:X}, "
                f"next starts 0x{cur['addr']:X}")
    return problems


def to_function_set(symbols, commit):
    """Convert symbols into a function set with provenance.

    Args:
        symbols: output of parse_symbols.
        commit: the upstream commit these came from.

    Returns:
        A dict with:
            "source_commit" - the commit string
            "count"         - how many symbols
            "functions"     - dict mapping name -> {"addr", "size"}

    Raises:
        ValueError: on a duplicate *name*. Two functions with one name means
            one silently shadows the other everywhere downstream.
    """
    functions = {}
    for sym in symbols:
        if sym["name"] in functions:
            raise ValueError(f"duplicate symbol name {sym['name']!r}")
        functions[sym["name"]] = {"addr": sym["addr"], "size": sym["size"]}
    return {"source_commit": commit, "count": len(functions),
            "functions": functions}


def diff_imports(old, new):
    """Report what changed between two imports.

    Args:
        old, new: function sets from to_function_set. `old` may be None for a
            first import.

    Returns:
        A dict with:
            "added"    - sorted names only in new
            "removed"  - sorted names only in old
            "moved"    - sorted list of dicts with "name", "from", "to" for
                         functions whose address changed
            "resized"  - sorted list of dicts with "name", "from", "to" for
                         functions whose size changed
            "from_commit" / "to_commit"
    """
    old_funcs = old["functions"] if old else {}
    new_funcs = new["functions"]

    moved, resized = [], []
    for name in sorted(set(old_funcs) & set(new_funcs)):
        before, after = old_funcs[name], new_funcs[name]
        if before["addr"] != after["addr"]:
            moved.append({"name": name, "from": before["addr"],
                          "to": after["addr"]})
        if before["size"] != after["size"]:
            resized.append({"name": name, "from": before["size"],
                            "to": after["size"]})

    return {
        "added": sorted(set(new_funcs) - set(old_funcs)),
        "removed": sorted(set(old_funcs) - set(new_funcs)),
        "moved": moved,
        "resized": resized,
        "from_commit": old["source_commit"] if old else None,
        "to_commit": new["source_commit"],
    }


def format_diff(diff):
    """Format an import diff."""
    lines = [f"import {diff['from_commit'] or '(first)'} -> {diff['to_commit']}"]
    for name in diff["added"]:
        lines.append(f"  + {name}")
    for name in diff["removed"]:
        lines.append(f"  - {name}")
    for m in diff["moved"]:
        lines.append(f"  ~ {m['name']} moved 0x{m['from']:X} -> 0x{m['to']:X}")
    for r in diff["resized"]:
        lines.append(f"  ~ {r['name']} resized 0x{r['from']:X} -> 0x{r['to']:X}")
    return "\n".join(lines)
