"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 70: Timing Regression Test

Assert that a fixed input reaches a known game state on a known frame --
catching a pacing bug that a frame-hash comparison cannot see.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


class Timeline:
    """An ordered record of which state was observed on which frame."""

    def __init__(self, observations=None):
        self.observations = list(observations or [])   # list of (frame, state)

    def record(self, frame, state):
        self.observations.append((frame, state))

    def states(self):
        """Return the set of states observed."""
        return {s for _, s in self.observations}

    def frame_of(self, state):
        """Return the first frame at which *state* was observed, or None."""
        for frame, s in self.observations:
            if s == state:
                return frame
        return None


def compare_content(a, b):
    """The weak check: did both timelines see the same set of states?

    This deliberately ignores *when*. It is the comparison most projects
    actually run, and section "What You Must Demonstrate" in the README is
    about showing what it misses.

    Returns:
        A dict with:
            "match"   - bool
            "missing" - sorted states in a but not b
            "extra"   - sorted states in b but not a
    """
    a_states, b_states = a.states(), b.states()
    missing = sorted(a_states - b_states)
    extra = sorted(b_states - a_states)
    return {"match": not missing and not extra,
            "missing": missing, "extra": extra}


def compare_timeline(a, b, tolerance=0):
    """The real check: same states, reached at the same frames.

    A state reached more than *tolerance* frames away from the reference is a
    failure even though the state itself appeared.

    Args:
        a: the reference Timeline.
        b: the Timeline under test.
        tolerance: allowed absolute frame difference.

    Returns:
        A dict with:
            "match"    - bool
            "missing"  - sorted states absent from b
            "mistimed" - list of dicts with "state", "expected", "actual",
                         "delta", sorted by expected frame
    """
    missing = []
    mistimed = []

    for frame, state in a.observations:
        actual = b.frame_of(state)
        if actual is None:
            if state not in missing:
                missing.append(state)
            continue
        delta = actual - frame
        if abs(delta) > tolerance:
            mistimed.append({"state": state, "expected": frame,
                             "actual": actual, "delta": delta})

    mistimed.sort(key=lambda m: m["expected"])
    return {"match": not missing and not mistimed,
            "missing": sorted(missing), "mistimed": mistimed}


def assert_reaches(timeline, state, frame, tolerance=0):
    """Assert a single milestone was reached at about the right frame.

    Returns:
        None if satisfied, otherwise a detail string.
    """
    actual = timeline.frame_of(state)
    if actual is None:
        return f"{state!r} was never reached"
    delta = actual - frame
    if abs(delta) > tolerance:
        return (f"{state!r} expected at frame {frame}, reached at {actual} "
                f"(delta {delta:+d})")
    return None


def format_comparison(result):
    """Format a timeline comparison."""
    if result["match"]:
        return "timeline matches"
    lines = ["timeline MISMATCH"]
    for s in result.get("missing", []):
        lines.append(f"  missing state: {s}")
    for m in result.get("mistimed", []):
        lines.append(f"  {m['state']}: expected frame {m['expected']}, "
                     f"got {m['actual']} (delta {m['delta']:+d})")
    return "\n".join(lines)
