"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 50: Project Regression Harness

A regression test runner that reads TOML config, executes binaries,
and compares output checksums against expected values.
"""

import hashlib
import subprocess
import sys

# ---------------------------------------------------------------------------
# TOML loading -- handle Python 3.11+ (tomllib) and older (tomli)
# ---------------------------------------------------------------------------

try:
    import tomllib                   # Python 3.11+
except ModuleNotFoundError:
    try:
        import tomli as tomllib      # pip install tomli
    except ModuleNotFoundError:
        tomllib = None


# ---------------------------------------------------------------------------
# Result dataclass-like dict
# ---------------------------------------------------------------------------

def make_result(name, status, expected_md5="", actual_md5="",
                exit_code_match=True, message=""):
    """Create a test result dict.

    Parameters
    ----------
    name : str
    status : str
        "pass", "fail", or "error"
    expected_md5 : str
    actual_md5 : str
    exit_code_match : bool
    message : str

    Returns
    -------
    dict
    """
    return {
        "name": name,
        "status": status,
        "expected_md5": expected_md5,
        "actual_md5": actual_md5,
        "exit_code_match": exit_code_match,
        "message": message,
    }


# ---------------------------------------------------------------------------
# Core functions -- complete the TODOs
# ---------------------------------------------------------------------------

def load_config(path):
    """Load and parse a TOML config file.

    Parameters
    ----------
    path : str
        Path to the .toml file.

    Returns
    -------
    dict
        Parsed TOML as a Python dict.

    Raises
    ------
    RuntimeError
        If tomllib is not available.
    FileNotFoundError
        If the file does not exist.
    """
    if tomllib is None:
        raise RuntimeError("TOML library not available")
    with open(path, "rb") as f:
        return tomllib.load(f)


def parse_config(config):
    """Extract the project name and test list from a parsed config.

    Parameters
    ----------
    config : dict
        Parsed TOML config.

    Returns
    -------
    tuple of (str, list of dict)
        (project_name, tests)
        Each test dict has: name, binary, args, input_file,
        expected_stdout_md5, expected_exit_code.
    """
    project_name = config["project"]["name"]
    tests = []
    for entry in config["tests"]:
        tests.append({
            "name": entry["name"],
            "binary": entry["binary"],
            "args": entry.get("args", []),
            "input_file": entry.get("input_file", ""),
            "expected_stdout_md5": entry.get("expected_stdout_md5", ""),
            "expected_exit_code": entry.get("expected_exit_code", 0),
        })
    return project_name, tests


def compute_md5(data):
    """Compute the MD5 hex digest of bytes data.

    Parameters
    ----------
    data : bytes

    Returns
    -------
    str
        32-character hex digest string.
    """
    return hashlib.md5(data).hexdigest()


def run_test_binary(binary, args, input_file="", timeout=30):
    """Run a binary with arguments and optional input file.

    Parameters
    ----------
    binary : str
        Path to the binary or command name.
    args : list of str
        Command-line arguments.
    input_file : str
        Path to a file whose contents are fed to stdin.
        If empty string, no stdin input.
    timeout : int
        Maximum seconds to wait.

    Returns
    -------
    tuple of (bytes, int)
        (stdout_data, exit_code)
        If the process times out, return (b"", -1).

    Use subprocess.run with capture_output=True.
    """
    cmd = [binary] + list(args)
    stdin_data = None
    if input_file:
        try:
            with open(input_file, "rb") as f:
                stdin_data = f.read()
        except FileNotFoundError:
            return b"", -1

    try:
        result = subprocess.run(
            cmd, input=stdin_data, capture_output=True, timeout=timeout
        )
    except subprocess.TimeoutExpired:
        return b"", -1
    except FileNotFoundError:
        return b"", -1

    return result.stdout, result.returncode


def run_single_test(test):
    """Run a single test and return a result dict.

    Parameters
    ----------
    test : dict
        A test spec from parse_config.

    Returns
    -------
    dict
        A result dict from make_result.
    """
    stdout_data, exit_code = run_test_binary(
        test["binary"], test["args"], test["input_file"]
    )

    if exit_code == -1:
        return make_result(
            test["name"], "error",
            message="binary not found, or timed out",
        )

    actual_md5 = compute_md5(stdout_data)
    expected_md5 = test["expected_stdout_md5"]

    md5_match = (not expected_md5) or (actual_md5 == expected_md5)
    exit_match = exit_code == test["expected_exit_code"]

    if md5_match and exit_match:
        return make_result(
            test["name"], "pass",
            expected_md5=expected_md5, actual_md5=actual_md5,
            exit_code_match=True,
        )

    problems = []
    if not md5_match:
        problems.append(f"stdout md5 {actual_md5} != {expected_md5}")
    if not exit_match:
        problems.append(
            f"exit code {exit_code} != {test['expected_exit_code']}"
        )

    return make_result(
        test["name"], "fail",
        expected_md5=expected_md5, actual_md5=actual_md5,
        exit_code_match=exit_match,
        message="; ".join(problems),
    )


def run_all_tests(config_path):
    """Run all tests defined in a TOML config file.

    Parameters
    ----------
    config_path : str
        Path to the .toml config file.

    Returns
    -------
    dict with keys:
        "project_name" : str
        "results"      : list of result dicts
        "passed"       : int
        "failed"       : int
        "errors"       : int
    """
    project_name, tests = parse_config(load_config(config_path))
    results = [run_single_test(test) for test in tests]

    return {
        "project_name": project_name,
        "results": results,
        "passed": sum(1 for r in results if r["status"] == "pass"),
        "failed": sum(1 for r in results if r["status"] == "fail"),
        "errors": sum(1 for r in results if r["status"] == "error"),
    }


# ---------------------------------------------------------------------------
# Report formatting
# ---------------------------------------------------------------------------

def format_report(summary):
    """Format a test summary as a human-readable report string.

    Parameters
    ----------
    summary : dict
        From run_all_tests.

    Returns
    -------
    str
    """
    lines = []
    lines.append(f"=== Regression Test Results: {summary['project_name']} ===")
    lines.append("")

    for r in summary["results"]:
        tag = r["status"].upper()
        lines.append(f"[{tag}] {r['name']}")
        if r["actual_md5"]:
            if r["status"] == "pass":
                lines.append(f"  MD5: {r['actual_md5']} (match)")
            else:
                lines.append(f"  MD5: {r['actual_md5']} "
                             f"(expected: {r['expected_md5']})")
        if r["message"]:
            lines.append(f"  {r['message']}")
        lines.append("")

    lines.append(f"Results: {summary['passed']} passed, "
                 f"{summary['failed']} failed, "
                 f"{summary['errors']} errors")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python regression_runner.py <config.toml>")
        sys.exit(1)

    summary = run_all_tests(sys.argv[1])
    print(format_report(summary))
    sys.exit(0 if summary["failed"] == 0 and summary["errors"] == 0 else 1)
