"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 104: Matching Decomp as Oracle

Function-level differential testing against a matching decompilation, with
honest coverage reporting.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


def compare_function(name, cases, decomp_fn, recomp_fn):
    """Differentially test one function against the decomp's version.

    Args:
        name: function name.
        cases: list of argument tuples.
        decomp_fn: the decompiled reference.
        recomp_fn: your recompiled version.

    Returns:
        A dict with:
            "name"      - the function name
            "cases"     - how many cases ran
            "status"    - "pass", "fail" or "error"
            "failures"  - list of dicts with "case", "expected", "actual"
            "message"   - detail for "error"

    A function that raises on some case is "error" -- distinct from a wrong
    answer, because the two send you to different places.
    """
    failures = []
    try:
        for case in cases:
            expected = decomp_fn(*case)
            actual = recomp_fn(*case)
            if expected != actual:
                failures.append({"case": case, "expected": expected,
                                 "actual": actual})
    except Exception as exc:
        return {"name": name, "cases": len(cases), "status": "error",
                "failures": failures, "message": str(exc)}

    return {"name": name, "cases": len(cases),
            "status": "fail" if failures else "pass",
            "failures": failures, "message": ""}


def run_suite(suite, decomp, recomp):
    """Run every function in the suite.

    Args:
        suite: dict mapping function name -> list of argument tuples.
        decomp: dict mapping name -> reference callable.
        recomp: dict mapping name -> callable under test.

    Returns:
        A dict with:
            "results"  - list of compare_function dicts, sorted by name
            "passed" / "failed" / "errors" - counts
            "missing"  - sorted names in the suite with no implementation on
                         one side or the other
    """
    results, missing = [], []
    for name in sorted(suite):
        if name not in decomp or name not in recomp:
            missing.append(name)
            continue
        results.append(compare_function(name, suite[name], decomp[name],
                                        recomp[name]))

    return {
        "results": results,
        "passed": sum(1 for r in results if r["status"] == "pass"),
        "failed": sum(1 for r in results if r["status"] == "fail"),
        "errors": sum(1 for r in results if r["status"] == "error"),
        "missing": missing,
    }


def coverage(suite_result, all_functions):
    """How much of the program is actually covered?

    Args:
        suite_result: output of run_suite.
        all_functions: every function in the binary.

    Returns:
        A dict with:
            "tested"   - how many functions the suite exercised
            "total"    - len(all_functions)
            "fraction" - tested / total, 0.0 when total is 0
            "untested" - sorted names with no test
    """
    tested = {r["name"] for r in suite_result["results"]}
    total = len(all_functions)
    return {
        "tested": len(tested),
        "total": total,
        "fraction": (len(tested) / total) if total else 0.0,
        "untested": sorted(n for n in all_functions if n not in tested),
    }


def honest_report(suite_result, cov):
    """A report that refuses to describe low coverage as validation.

    Rules:
      - any failures or errors -> "N function(s) diverge from the decomp."
      - all passed and coverage >= 0.8 -> "All N tested functions match the
        decomp (P% coverage)."
      - all passed and coverage < 0.8  -> "All N tested functions match, but
        only P% of the binary is covered -- this is not validation of the
        build."

    Returns:
        A string.
    """
    bad = suite_result["failed"] + suite_result["errors"]
    if bad:
        return f"{bad} function(s) diverge from the decomp."

    tested = cov["tested"]
    pct = f"{cov['fraction'] * 100:.1f}%"
    if cov["fraction"] >= 0.8:
        return f"All {tested} tested functions match the decomp ({pct} coverage)."
    return (f"All {tested} tested functions match, but only {pct} of the "
            f"binary is covered -- this is not validation of the build.")
