"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 67: Triage Tool

Deduplicate failing reproducers by cause, then rank the surviving groups
by how much of the program they actually affect.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


from collections import Counter

KINDS = ("crash", "divergence")


def fingerprint(report):
    """Return a dedup key for a failure report.

    Args:
        report: dict with "func" (int address), "insn" (str) and "kind"
            (one of KINDS).

    Returns:
        A tuple (func, insn, kind). Two reports with the same fingerprint are
        the same bug.

    Raises:
        ValueError: on an unknown kind. A report you cannot classify would
            form its own group and quietly look like a distinct bug.
    """
    kind = report["kind"]
    if kind not in KINDS:
        raise ValueError(f"unknown failure kind {kind!r}")
    return (report["func"], report["insn"], kind)


def deduplicate(reports):
    """Group reports by fingerprint.

    Returns:
        A list of dicts, one per distinct bug, each with:
            "fingerprint" - the key
            "func"        - the function address
            "insn"        - the instruction
            "kind"        - the kind
            "count"       - how many reports collapsed into this group
            "examples"    - the reports themselves, in input order

    Groups are returned in first-seen order so the output is stable.
    """
    groups = {}
    for report in reports:
        key = fingerprint(report)
        group = groups.get(key)
        if group is None:
            groups[key] = {
                "fingerprint": key,
                "func": report["func"],
                "insn": report["insn"],
                "kind": report["kind"],
                "count": 1,
                "examples": [report],
            }
        else:
            group["count"] += 1
            group["examples"].append(report)
    return list(groups.values())


def rank(groups, trace_counts):
    """Order groups by how much of the program they affect.

    Sort key, highest first:
      1. execution count of the group's function (0 if it never ran)
      2. the group's report count
      3. divergences before crashes -- a quiet wrong answer is worse than a
         loud stop, because nothing tells you about it
      4. function address, so the order is deterministic

    Args:
        groups: output of deduplicate().
        trace_counts: dict mapping function address -> times executed.

    Returns:
        A new list, sorted. Each group gains a "reach" key with its execution
        count.
    """
    annotated = []
    for group in groups:
        g = dict(group)
        g["reach"] = trace_counts.get(g["func"], 0)
        annotated.append(g)

    # A quiet divergence outranks a loud crash at equal reach: nothing tells
    # you about a wrong answer.
    return sorted(annotated, key=lambda g: (
        -g["reach"],
        -g["count"],
        0 if g["kind"] == "divergence" else 1,
        g["func"],
    ))


def triage(reports, trace_counts):
    """Deduplicate and rank in one step.

    Returns:
        A dict with:
            "total"   - how many reports came in
            "unique"  - how many distinct bugs
            "groups"  - the ranked groups
    """
    groups = deduplicate(reports)
    return {
        "total": len(reports),
        "unique": len(groups),
        "groups": rank(groups, trace_counts),
    }


def format_triage(result):
    """Format a triage result as a work list."""
    lines = [f"{result['total']} report(s) -> {result['unique']} distinct bug(s)"]
    for i, g in enumerate(result["groups"], 1):
        lines.append(
            f"  {i}. 0x{g['func']:08X} {g['insn']:12s} {g['kind']:10s} "
            f"x{g['count']:<4d} reach={g['reach']}")
    return "\n".join(lines)
