"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 77: Endianness Two Ways

Byte-swap-on-access versus swapped storage with an address XOR, compared
on read-heavy and write-heavy workloads.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


def swap32(value):
    """Byte-swap a 32-bit value.

    Returns:
        The swapped value, masked to 32 bits.
    """
    return (((value & 0x000000FF) << 24) |
            ((value & 0x0000FF00) << 8) |
            ((value & 0x00FF0000) >> 8) |
            ((value & 0xFF000000) >> 24))


def byte_xor(addr):
    """The address XOR that selects the right byte within a swapped word.

    With 32-bit words stored byte-swapped, byte N of a guest word lives at
    host offset N ^ 3.
    """
    return addr ^ 3


class SwapOnAccess:
    """Store native, swap on every word access.

    Attributes:
        swaps: how many byte-swaps were performed.
    """

    def __init__(self, size):
        self.memory = bytearray(size)
        self.swaps = 0

    def read32(self, addr):
        """Read a big-endian 32-bit word, swapping to host order."""
        self.swaps += 1
        stored = int.from_bytes(self.memory[addr:addr + 4], "little")
        return swap32(stored)

    def read8(self, addr):
        """Read one byte. No swap is needed for a single byte."""
        return self.memory[addr]

    def write32(self, addr, value):
        """Write a 32-bit word in guest order, swapping on the way in."""
        self.swaps += 1
        stored = swap32(value)
        self.memory[addr:addr + 4] = stored.to_bytes(4, "little")


class SwappedStorage:
    """Store pre-swapped, so aligned word access is free.

    Attributes:
        xors: how many address XORs were performed (sub-word accesses only).
        swaps: how many byte-swaps were performed -- should stay at zero for
            aligned word access, which is the entire point.
    """

    def __init__(self, size):
        self.memory = bytearray(size)
        self.xors = 0
        self.swaps = 0

    def read32(self, addr):
        """Read an aligned 32-bit word. No swap, no XOR."""
        # Already stored in host order: no swap, no XOR. This is the whole point.
        return int.from_bytes(self.memory[addr:addr + 4], "little")

    def read8(self, addr):
        """Read one byte, XOR-ing the address to find it."""
        self.xors += 1
        return self.memory[byte_xor(addr)]

    def write32(self, addr, value):
        """Write an aligned 32-bit word. No swap, no XOR."""
        self.memory[addr:addr + 4] = value.to_bytes(4, "little")


def compare(workload, size=0x100):
    """Run a workload through both strategies and compare cost and results.

    Args:
        workload: list of ("w32", addr, value) / ("r32", addr, None) /
            ("r8", addr, None) tuples.
        size: memory size for both.

    Returns:
        A dict with:
            "agree"          - bool, did every read match?
            "mismatches"     - list of (index, op, addr, a_value, b_value)
            "swap_cost"      - swaps performed by SwapOnAccess
            "storage_cost"   - xors performed by SwappedStorage
    """
    a = SwapOnAccess(size)
    b = SwappedStorage(size)
    mismatches = []

    for i, (op, addr, value) in enumerate(workload):
        if op == "w32":
            a.write32(addr, value)
            b.write32(addr, value)
        elif op == "r32":
            x, y = a.read32(addr), b.read32(addr)
            if x != y:
                mismatches.append((i, op, addr, x, y))
        elif op == "r8":
            x, y = a.read8(addr), b.read8(addr)
            if x != y:
                mismatches.append((i, op, addr, x, y))
        else:
            raise ValueError(f"unknown op {op!r}")

    return {"agree": not mismatches, "mismatches": mismatches,
            "swap_cost": a.swaps, "storage_cost": b.xors}
