"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 57: Manifest-Driven Pipeline

Convert a pipeline driven by command-line flags into one driven by a
declarative manifest, keeping derived state out of the source file.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
import os


# Sections a manifest may contain. Anything else is an error -- a typo'd
# section name that is silently ignored is a decision that quietly stopped
# applying.
KNOWN_SECTIONS = {"project", "input", "entrypoint", "imports", "memory"}

# Sections that must NEVER appear: these hold derived state, which belongs in
# the output directory as a cache, not in the manifest as a source.
FORBIDDEN_SECTIONS = {"discovered", "cache", "generated", "analysis"}


class ManifestError(Exception):
    """Raised for a manifest that cannot be trusted."""


def parse_manifest(text):
    """Parse an INI-like manifest.

        [project]
        name = worms
        base = 0x82000000

        [entrypoint.functions]
        0x82236F38 = tail-call discovery missed
        0x82E80100 = runtime-harvested (tolerant dispatch boot)

        [imports]
        XUsbcamGetState = purge:8

    Rules:
      - `[section]` starts a section; `[a.b]` is a subsection, stored under the
        key "a.b".
      - `key = value`, both stripped.
      - Blank lines and lines starting with "#" are ignored.
      - A key before any section header is an error.

    Returns:
        A dict mapping section name -> dict of key/value strings, preserving
        insertion order.

    Raises:
        ManifestError: on a key outside a section, or a malformed line.
    """
    sections = {}
    current = None

    for number, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].strip()
            sections.setdefault(current, {})
            continue

        if current is None:
            raise ManifestError(f"line {number}: key outside any section: {line!r}")
        if "=" not in line:
            raise ManifestError(f"line {number}: malformed line: {line!r}")

        key, _, value = line.partition("=")
        sections[current][key.strip()] = value.strip()

    return sections


def validate(manifest):
    """Check a parsed manifest, raising on anything untrustworthy.

    Rejects:
      - any section whose top-level name is in FORBIDDEN_SECTIONS
      - any section whose top-level name is not in KNOWN_SECTIONS
      - a missing [project] section, or a [project] without a name

    Returns:
        True if the manifest is valid.

    Raises:
        ManifestError: with a message naming the offending section.
    """
    for name in manifest:
        top = name.split(".")[0]
        if top in FORBIDDEN_SECTIONS:
            raise ManifestError(
                f"section [{name}] holds derived state; it belongs in the "
                f"output directory, not the manifest")
        if top not in KNOWN_SECTIONS:
            raise ManifestError(f"unknown section [{name}]")

    project = manifest.get("project")
    if project is None:
        raise ManifestError("missing [project] section")
    if not project.get("name"):
        raise ManifestError("[project] has no name")

    return True


def hints(manifest):
    """Extract function-entry hints with their recorded provenance.

    Reads the "entrypoint.functions" section, where each key is a hex address
    and each value is a free-text note saying where the hint came from.

    Returns:
        A list of dicts with keys "addr" (int) and "source" (str), sorted by
        address. Returns [] if the section is absent.

    Raises:
        ManifestError: if a hint has an empty note. An address with no
            recorded provenance is the thing Module 14 warns about -- you
            cannot later tell a runtime-verified hint from a pointer-scan guess.
    """
    section = manifest.get("entrypoint.functions")
    if not section:
        return []

    out = []
    for key, note in section.items():
        if not note.strip():
            raise ManifestError(
                f"hint {key} has no recorded source; a bare address cannot be "
                f"told apart from a guess six months from now")
        out.append({"addr": int(key, 16), "source": note.strip()})

    return sorted(out, key=lambda h: h["addr"])


def resolve_overrides(manifest):
    """Parse the [imports] section into per-import overrides.

    Each value is a comma-separated list of `field:value` pairs:

        XUsbcamGetState = purge:8
        SomeOtherImport = purge:4, mode:stub

    Returns:
        A dict mapping import name -> dict of field -> value, with "purge"
        converted to int. Returns {} if the section is absent.

    Raises:
        ManifestError: on a malformed pair or a non-integer purge.
    """
    section = manifest.get("imports")
    if not section:
        return {}

    out = {}
    for name, spec in section.items():
        fields = {}
        for item in spec.split(","):
            item = item.strip()
            if not item:
                continue
            if ":" not in item:
                raise ManifestError(f"{name}: malformed override {item!r}")
            field, _, value = item.partition(":")
            field, value = field.strip(), value.strip()
            if field == "purge":
                try:
                    value = int(value, 0)
                except ValueError:
                    raise ManifestError(f"{name}: purge must be an integer, got {value!r}")
            fields[field] = value
        out[name] = fields

    return out


def derived_path(manifest, outdir):
    """Return where derived state for this project should be written.

    Derived state is a cache. It goes in the output directory, named after the
    project, and it is never written back into the manifest.

    Returns:
        A path string: "<outdir>/<project name>.derived.json"
    """
    name = manifest["project"]["name"]
    return os.path.join(outdir, f"{name}.derived.json")
