"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 99: Instrument a Hybrid

Count registered functions, hook hits and fallbacks, and report the
crossover metric -- what fraction of execution is actually native.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


class Interceptor:
    """An interception registry with the counters the design owes you."""

    def __init__(self, fallback=None):
        self.registry = {}          # addr -> (callable, instruction_count)
        self.fallback = fallback    # callable(addr) -> instruction_count
        self.native_calls = 0
        self.fallback_calls = 0
        self.native_instructions = 0
        self.fallback_instructions = 0
        self.crashes = 0

    def register(self, addr, func, instructions=1):
        """Register a recompiled function at a guest address."""
        self.registry[addr] = (func, instructions)

    def dispatch(self, addr):
        """Run the recompiled function if there is one, else fall back.

        A registered function that raises is counted as a crash and falls back,
        which is what the real implementations do -- and is exactly why the
        counters matter.

        Returns:
            The number of instructions executed.

        Raises:
            RuntimeError: if nothing is registered and there is no fallback.
        """
        entry = self.registry.get(addr)

        if entry is not None:
            func, instructions = entry
            try:
                func()
            except Exception:
                # Exactly what the real implementations do: roll back and let the
                # fallback cover it. The counter is the only trace it leaves.
                self.crashes += 1
            else:
                self.native_calls += 1
                self.native_instructions += instructions
                return instructions

        if self.fallback is None:
            raise RuntimeError(f"nothing registered at 0x{addr:X} and no fallback")

        instructions = self.fallback(addr)
        self.fallback_calls += 1
        self.fallback_instructions += instructions
        return instructions

    def crossover(self):
        """The fraction of executed instructions that ran as native code.

        Returns:
            A float in [0.0, 1.0]. Zero executed instructions gives 0.0.
        """
        total = self.native_instructions + self.fallback_instructions
        return (self.native_instructions / total) if total else 0.0

    def stats(self):
        """Return every counter, plus the crossover."""
        return {
            "registered": len(self.registry),
            "native_calls": self.native_calls,
            "fallback_calls": self.fallback_calls,
            "native_instructions": self.native_instructions,
            "fallback_instructions": self.fallback_instructions,
            "crashes": self.crashes,
            "crossover": self.crossover(),
        }


def honest_summary(stats):
    """A claim about a hybrid build that does not overstate it.

    Rules, in order:
      - no instructions executed -> "Nothing has executed."
      - crossover == 0.0         -> "N functions registered, but 0% of executed
                                     instructions ran native -- the fallback is
                                     running this program."
      - crossover == 1.0         -> "All executed instructions ran native code
                                     (N functions registered)."
      - otherwise                -> "P% of executed instructions ran native
                                     (N functions registered)."

    Then, if crashes > 0, append " C recompiled function(s) crashed and fell
    back."

    Returns:
        A string.
    """
    executed = stats["native_instructions"] + stats["fallback_instructions"]
    registered = stats["registered"]
    crossover = stats["crossover"]

    if executed == 0:
        claim = "Nothing has executed."
    elif crossover == 0.0:
        claim = (f"{registered} functions registered, but 0% of executed "
                 f"instructions ran native -- the fallback is running this "
                 f"program.")
    elif crossover == 1.0:
        claim = (f"All executed instructions ran native code "
                 f"({registered} functions registered).")
    else:
        claim = (f"{crossover * 100:.1f}% of executed instructions ran native "
                 f"({registered} functions registered).")

    if stats["crashes"]:
        claim += (f" {stats['crashes']} recompiled function(s) crashed and "
                  f"fell back.")

    return claim
