"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 121: Harness Validation

Inject known bugs into a measurement harness and confirm it detects each
one -- because a check that cannot fail is not a check.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


class Mutation:
    """A named defect that can be applied to a subject and undone.

    Attributes:
        name: what this mutation breaks.
        apply: callable(subject) -> mutated subject.
        should_detect: whether a competent harness ought to catch it. A
            mutation marked False is a control -- if the harness "catches" it,
            the harness is reporting noise.
    """

    def __init__(self, name, apply, should_detect=True):
        self.name = name
        self.apply = apply
        self.should_detect = should_detect


def validate_harness(harness, subject, mutations):
    """Inject each mutation and check whether the harness notices.

    Args:
        harness: callable(subject) -> bool, True when the subject looks healthy.
        subject: the unmutated subject.
        mutations: list of Mutation.

    Returns:
        A dict with:
            "baseline"  - bool, did the harness pass the unmutated subject?
            "results"   - list of dicts with "name", "detected",
                          "should_detect" and "outcome"
            "caught"    - how many should-detect mutations were caught
            "escaped"   - sorted names of should-detect mutations that were not
            "false_alarms" - sorted names of control mutations wrongly flagged

    "outcome" is one of:
        "caught"      - should detect, and did
        "escaped"     - should detect, did not          <- the finding
        "correctly_ignored" - should not detect, did not
        "false_alarm" - should not detect, but did

    If the baseline fails, the harness is broken before any mutation and the
    rest of the results mean nothing -- report the baseline first.
    """
    baseline = bool(harness(subject))

    results, escaped, false_alarms = [], [], []
    caught = 0

    for mutation in mutations:
        detected = not bool(harness(mutation.apply(subject)))
        if mutation.should_detect:
            outcome = "caught" if detected else "escaped"
            if detected:
                caught += 1
            else:
                escaped.append(mutation.name)
        else:
            outcome = "false_alarm" if detected else "correctly_ignored"
            if detected:
                false_alarms.append(mutation.name)

        results.append({"name": mutation.name, "detected": detected,
                        "should_detect": mutation.should_detect,
                        "outcome": outcome})

    return {"baseline": baseline, "results": results, "caught": caught,
            "escaped": sorted(escaped), "false_alarms": sorted(false_alarms)}


def report(result):
    """Format a harness validation."""
    lines = []
    if not result["baseline"]:
        lines.append("BASELINE FAILED: the harness rejects a healthy subject. "
                     "Nothing below is meaningful.")
    lines.append(f"caught {result['caught']} of "
                 f"{result['caught'] + len(result['escaped'])} "
                 f"detectable mutation(s)")
    for name in result["escaped"]:
        lines.append(f"  ESCAPED: {name} -- the harness is blind to this")
    for name in result["false_alarms"]:
        lines.append(f"  FALSE ALARM: {name} -- the harness flags healthy code")
    return "\n".join(lines)
