"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 35: SH-2 Delay Slot Lifter

Lift SH-2 instructions to pseudo-C with correct delay slot handling.
"""

import sys
import os
import struct

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


# ---------------------------------------------------------------------------
# SH-2 Decoder
# ---------------------------------------------------------------------------

def _sign_extend_8(val):
    """Sign-extend an 8-bit value to a Python int."""
    if val & 0x80:
        return val - 0x100
    return val


def _sign_extend_12(val):
    """Sign-extend a 12-bit value to a Python int."""
    if val & 0x800:
        return val - 0x1000
    return val


def decode_sh2(data, offset, base_address=0):
    """Decode a single 16-bit SH-2 instruction.

    Args:
        data: bytes of SH-2 machine code (big-endian).
        offset: byte offset into data.
        base_address: address of the first byte of data.

    Returns:
        A dict with keys:
            "address"    - int, the instruction's address
            "raw"        - int, the raw 16-bit instruction word
            "mnemonic"   - str, e.g. "MOV", "ADD", "BRA"
            "has_delay"  - bool, True if this instruction has a delay slot
            "rn"         - int or None, destination register number
            "rm"         - int or None, source register number
            "disp"       - int or None, signed displacement (for branches)
            "target"     - int or None, computed branch target address

        Returns None if offset is out of range.

    Encoding patterns (big-endian 16-bit word):
        MOV Rm, Rn:    0110 nnnn mmmm 0011
        ADD Rm, Rn:    0011 nnnn mmmm 1100
        CMP/EQ Rm, Rn: 0011 nnnn mmmm 0000
        BT disp:       1000 1001 dddd dddd
        BF disp:       1000 1011 dddd dddd
        BRA disp:      1010 dddd dddd dddd
        JSR @Rm:       0100 mmmm 0000 1011
        RTS:           0000 0000 0000 1011
    """
    if offset + 2 > len(data):
        return None

    word = struct.unpack_from(">H", data, offset)[0]
    address = base_address + offset

    instr = {
        "address": address,
        "raw": word,
        "mnemonic": "UNKNOWN",
        "has_delay": False,
        "rn": None,
        "rm": None,
        "disp": None,
        "target": None,
    }

    if word == 0x000B:                          # RTS
        instr["mnemonic"] = "RTS"
        instr["has_delay"] = True
    elif (word & 0xF00F) == 0x6003:             # MOV Rm, Rn
        instr["mnemonic"] = "MOV"
        instr["rn"] = (word >> 8) & 0xF
        instr["rm"] = (word >> 4) & 0xF
    elif (word & 0xF00F) == 0x300C:             # ADD Rm, Rn
        instr["mnemonic"] = "ADD"
        instr["rn"] = (word >> 8) & 0xF
        instr["rm"] = (word >> 4) & 0xF
    elif (word & 0xF00F) == 0x3000:             # CMP/EQ Rm, Rn
        instr["mnemonic"] = "CMP/EQ"
        instr["rn"] = (word >> 8) & 0xF
        instr["rm"] = (word >> 4) & 0xF
    elif (word & 0xFF00) == 0x8900:             # BT disp
        instr["mnemonic"] = "BT"
        instr["has_delay"] = True
        instr["disp"] = _sign_extend_8(word & 0xFF)
        instr["target"] = address + 4 + instr["disp"] * 2
    elif (word & 0xFF00) == 0x8B00:             # BF disp
        instr["mnemonic"] = "BF"
        instr["has_delay"] = True
        instr["disp"] = _sign_extend_8(word & 0xFF)
        instr["target"] = address + 4 + instr["disp"] * 2
    elif (word & 0xF000) == 0xA000:             # BRA disp
        instr["mnemonic"] = "BRA"
        instr["has_delay"] = True
        instr["disp"] = _sign_extend_12(word & 0xFFF)
        instr["target"] = address + 4 + instr["disp"] * 2
    elif (word & 0xF0FF) == 0x400B:             # JSR @Rm
        instr["mnemonic"] = "JSR"
        instr["has_delay"] = True
        instr["rm"] = (word >> 8) & 0xF

    return instr


# ---------------------------------------------------------------------------
# Lifter
# ---------------------------------------------------------------------------

def lift_instruction(instr):
    """Lift a single decoded SH-2 instruction to pseudo-C.

    Args:
        instr: dict from decode_sh2().

    Returns:
        A string of pseudo-C code (without the delay slot handling --
        that is done by lift_block).

    Output for each mnemonic:
        MOV:    "regs[{rn}] = regs[{rm}];"
        ADD:    "regs[{rn}] = regs[{rn}] + regs[{rm}];"
        CMP/EQ: "T = (regs[{rn}] == regs[{rm}]);"
        BT:     "if (T) goto label_{target:08X};"
        BF:     "if (!T) goto label_{target:08X};"
        BRA:    "goto label_{target:08X};"
        JSR:    "PR = 0x{address+4:08X}; goto *regs[{rm}];"
        RTS:    "goto *PR;"
        UNKNOWN: "/* unknown: 0x{raw:04X} */;"
    """
    mnemonic = instr["mnemonic"]
    rn, rm = instr["rn"], instr["rm"]
    target = instr["target"]

    if mnemonic == "MOV":
        return f"regs[{rn}] = regs[{rm}];"
    if mnemonic == "ADD":
        return f"regs[{rn}] = regs[{rn}] + regs[{rm}];"
    if mnemonic == "CMP/EQ":
        return f"T = (regs[{rn}] == regs[{rm}]);"
    if mnemonic == "BT":
        return f"if (T) goto label_{target:08X};"
    if mnemonic == "BF":
        return f"if (!T) goto label_{target:08X};"
    if mnemonic == "BRA":
        return f"goto label_{target:08X};"
    if mnemonic == "JSR":
        return f"PR = 0x{instr['address'] + 4:08X}; goto *regs[{rm}];"
    if mnemonic == "RTS":
        return "goto *PR;"
    return f"/* unknown: 0x{instr['raw']:04X} */;"


def lift_block(data, base_address=0):
    """Lift a block of SH-2 instructions to pseudo-C with delay slot handling.

    The key rule: when an instruction has a delay slot (has_delay=True),
    the next instruction is the delay slot. It must be lifted BEFORE the
    branch instruction's C code.

    The output should include comments showing the original address and
    mnemonic, then the C code.

    Args:
        data: bytes of SH-2 code (big-endian).
        base_address: address of the first byte.

    Returns:
        A list of strings (lines of pseudo-C).
    """
    lines = []
    offset = 0

    while offset < len(data):
        instr = decode_sh2(data, offset, base_address)
        if instr is None:
            break

        comment = f"/* {instr['address']:08X}: {instr['mnemonic']} */"

        if instr["has_delay"]:
            delay = decode_sh2(data, offset + 2, base_address)
            lines.append(comment)
            if delay is not None:
                # The delay slot executes BEFORE the branch takes effect,
                # so its C has to be emitted first.
                lines.append(lift_instruction(delay) + "   // delay slot")
            lines.append(lift_instruction(instr))
            offset += 4
        else:
            lines.append(comment)
            lines.append(lift_instruction(instr))
            offset += 2

    return lines


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # Example: MOV R0,R1 ; CMP/EQ R2,R1 ; BT +4 ; ADD R3,R0 ; (target) RTS; NOP
    #
    # MOV R0, R1:   0x6103  -> 0110 0001 0000 0011
    # CMP/EQ R2,R1: 0x3120  -> 0011 0001 0010 0000
    # BT +2:        0x8902  -> 1000 1001 0000 0010  (target = addr+4+2*2 = addr+8)
    # ADD R3, R0:   0x303C  -> 0011 0000 0011 1100  (delay slot of BT)
    # RTS:          0x000B  -> 0000 0000 0000 1011
    # NOP (MOV R0,R0): 0x6003 -> delay slot of RTS

    program = struct.pack(">HHHHHH",
        0x6103,  # MOV R0, R1
        0x3120,  # CMP/EQ R2, R1
        0x8902,  # BT +2
        0x303C,  # ADD R3, R0  (delay slot of BT)
        0x000B,  # RTS
        0x6003,  # MOV R0, R0 (delay slot of RTS, effectively NOP)
    )

    lines = lift_block(program, base_address=0x06000000)
    if lines is None:
        print("lift_block() returned None -- implement the TODO sections.")
        return

    for line in lines:
        print(line)


if __name__ == "__main__":
    main()
