"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 79: Function Ordering

Generate a linker ordering file from an execution trace and estimate the
change in instruction-cache behaviour.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


from collections import Counter


def call_counts(trace):
    """Count how often each function appears in the trace.

    Returns:
        A dict mapping name -> count.
    """
    return dict(Counter(trace))


def order_by_heat(counts, all_functions):
    """Produce a linker ordering: hottest first, cold functions after.

    Args:
        counts: name -> call count.
        all_functions: every function name, including ones never called.

    Returns:
        A list of names. Called functions come first, ordered by count
        descending then name ascending; never-called functions follow, sorted
        by name. The tie-break matters: an unstable ordering file produces a
        different binary on every build.
    """
    called = [n for n in all_functions if counts.get(n, 0) > 0]
    uncalled = [n for n in all_functions if counts.get(n, 0) == 0]
    called.sort(key=lambda n: (-counts[n], n))
    uncalled.sort()
    return called + uncalled


def layout(order, sizes):
    """Assign addresses by laying functions out in *order*, starting at 0.

    Args:
        order: list of names.
        sizes: dict mapping name -> size in bytes.

    Returns:
        A dict mapping name -> start address.

    Raises:
        KeyError: if a name in *order* has no size.
    """
    addresses = {}
    cursor = 0
    for name in order:
        addresses[name] = cursor
        cursor += sizes[name]
    return addresses


def estimate_cache_misses(trace, addresses, sizes, line_size=64):
    """Estimate distinct cache lines touched by the trace.

    For each call in the trace, the function occupies the lines spanning
    [addr, addr + size). Count the distinct lines across the whole trace --
    fewer distinct lines means better locality.

    Returns:
        The number of distinct cache lines.
    """
    lines = set()
    for name in trace:
        start = addresses[name]
        end = start + sizes[name]
        for line in range(start // line_size, (end - 1) // line_size + 1):
            lines.add(line)
    return len(lines)


def compare_layouts(trace, all_functions, sizes, original_order, line_size=64):
    """Compare the original layout against a heat-ordered one.

    Returns:
        A dict with:
            "original_lines"  - distinct lines under the original order
            "ordered_lines"   - distinct lines under the heat order
            "improvement"     - fraction reduced, 0.0 if no improvement
            "order"           - the heat-ordered function list
    """
    counts = call_counts(trace)
    heat = order_by_heat(counts, all_functions)

    original_lines = estimate_cache_misses(
        trace, layout(original_order, sizes), sizes, line_size)
    ordered_lines = estimate_cache_misses(
        trace, layout(heat, sizes), sizes, line_size)

    improvement = 0.0
    if original_lines and ordered_lines < original_lines:
        improvement = (original_lines - ordered_lines) / original_lines

    return {"original_lines": original_lines, "ordered_lines": ordered_lines,
            "improvement": improvement, "order": heat}
