"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 91: Stack to Locals

Compute static stack depth for a stack VM and emit numbered C locals
instead of a runtime stack.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


class StackError(Exception):
    """Raised when the stack does not balance."""


# An instruction is a dict:
#   {"pc": int, "op": str, "pops": int, "pushes": int,
#    "target": int or None}   # branch target, if any
#   Ops "branch" (unconditional) and "branch_if" (conditional) use target.
#   Op "return" ends a path.


def compute_depths(program):
    """Compute the stack depth on entry to every instruction.

    Starts at pc 0 with depth 0 and follows both fallthrough and branch edges.
    Unreachable instructions get no entry.

    Args:
        program: list of instruction dicts, indexed by position; each "pc" is
            its index.

    Returns:
        A dict mapping pc -> depth on entry.

    Raises:
        StackError: if two paths reach the same pc with different depths --
            that is the misparse signature, and guessing which is right would
            hide it.
    """
    depths = {}
    worklist = [(0, 0)]

    while worklist:
        pc, depth = worklist.pop()
        if pc >= len(program):
            continue

        known = depths.get(pc)
        if known is not None:
            if known != depth:
                raise StackError(
                    f"pc {pc} reached at depth {known} and {depth}")
            continue
        depths[pc] = depth

        insn = program[pc]
        after = depth - insn["pops"] + insn["pushes"]

        if insn["op"] == "return":
            continue
        if insn["op"] in ("branch", "branch_if") and insn["target"] is not None:
            worklist.append((insn["target"], after))
        if insn["op"] != "branch":
            worklist.append((pc + 1, after))

    return depths


def verify_balance(program):
    """Check the stack invariant across a whole program.

    Returns:
        A list of human-readable problem strings. Empty means it balances.

    Checks:
      - depth never goes negative (an instruction popped more than existed)
      - every "return" is reached at depth 0
      - compute_depths raises no conflict (reported as a problem, not an
        exception, so a corpus run can continue to the next program)
    """
    problems = []
    try:
        depths = compute_depths(program)
    except StackError as exc:
        return [f"conflicting depths: {exc}"]

    for pc, depth in sorted(depths.items()):
        insn = program[pc]
        if depth - insn["pops"] < 0:
            problems.append(
                f"pc {pc} ({insn['op']}) pops {insn['pops']} at depth {depth} "
                f"-- stack would go negative")
        if insn["op"] == "return" and depth != 0:
            problems.append(f"pc {pc} return at depth {depth}, expected 0")

    return problems


def max_depth(depths):
    """The most locals any point in the program needs."""
    return max(depths.values()) if depths else 0


def emit(program, depths):
    """Emit C using numbered locals instead of a runtime stack.

    Each instruction consumes its operands from the top slots and writes its
    result to the slot at its entry depth minus its pops.

        /*   46: find-var 0 */
        s[0] = op_find_var();
        /*   47: get-var 5  */
        s[1] = op_get_var();

    Args:
        program: the instructions.
        depths: output of compute_depths.

    Returns:
        A list of source lines, starting with the local declaration.
    """
    lines = [f"    value_t s[{max(max_depth(depths), 1)}];"]

    for pc in sorted(depths):
        insn = program[pc]
        depth = depths[pc]
        lines.append(f"    /* {pc:4d}: {insn['op']} */")
        if insn["pushes"]:
            slot = depth - insn["pops"]
            lines.append(f"    s[{slot}] = op_{insn['op'].replace('-', '_')}();")
        else:
            lines.append(f"    op_{insn['op'].replace('-', '_')}();")

    return lines
