"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 83: Input Verification

Identify the user's copy by hash, name the revision it found, warn clearly
on a mismatch, and print a provenance record.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


import hashlib


def hash_data(data):
    """Return the SHA-256 hex digest of *data*."""
    return hashlib.sha256(data).hexdigest()


def identify(data, known):
    """Identify which known revision *data* is.

    Args:
        data: the bytes.
        known: dict mapping sha256 hex -> revision label.

    Returns:
        The label, or None if unrecognised.
    """
    return known.get(hash_data(data))


def check(data, known, target):
    """Verify the user's copy against the revision this project targets.

    Args:
        data: the bytes they supplied.
        known: dict mapping sha256 hex -> label.
        target: the label this project targets.

    Returns:
        A dict with:
            "verdict" - "match", "known_mismatch" or "unknown"
            "found"   - the identified label, or None
            "digest"  - the hash of what they gave you
            "message" - what to tell them

    The message must always name the digest, so a bug report carries it even
    when the revision is unrecognised. No verdict refuses to proceed.
    """
    digest = hash_data(data)
    found = known.get(digest)
    short = digest[:16]

    if found == target:
        verdict = "match"
        message = f"Input identified as {found} (SHA-256 {short}...)."
    elif found is not None:
        verdict = "known_mismatch"
        message = (
            f"Expected: {target}\n"
            f"Found:    {found} (SHA-256 {short}...)\n"
            f"This project targets {target}. {found} has different function "
            f"addresses and the manifest hints will not apply. Proceeding "
            f"anyway -- expect unresolved calls.")
    else:
        verdict = "unknown"
        message = (
            f"Unrecognised input (SHA-256 {short}...). This project targets "
            f"{target}. Proceeding anyway; if it works, please report this "
            f"hash so it can be added.")

    return {"verdict": verdict, "found": found, "digest": digest,
            "message": message}


def provenance(data, known, target, tool_versions):
    """Build the provenance record for a run.

    Args:
        data: the input bytes.
        known: the revision table.
        target: the targeted label.
        tool_versions: dict mapping tool name -> version string.

    Returns:
        A dict with "digest", "identified", "target", "verdict" and "tools"
        (a sorted list of "name=version" strings, so the record is stable
        between runs and diffable).
    """
    result = check(data, known, target)
    return {
        "digest": result["digest"],
        "identified": result["found"],
        "target": target,
        "verdict": result["verdict"],
        "tools": sorted(f"{name}={version}" for name, version in tool_versions.items()),
    }


def format_provenance(record):
    """Format a provenance record for printing at startup."""
    lines = ["=== Provenance ==="]
    lines.append(f"  input:      {record['digest'][:16]}...")
    lines.append(f"  identified: {record['identified'] or '(unrecognised)'}")
    lines.append(f"  target:     {record['target']}")
    lines.append(f"  verdict:    {record['verdict']}")
    for t in record["tools"]:
        lines.append(f"  tool:       {t}")
    return "\n".join(lines)
