"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 22: Ghidra Script - Function Exporter

Export all identified functions from a Ghidra project to JSON.

When run inside Ghidra, the `ghidra` and `currentProgram` variables
are provided automatically. For testing, we use a mock module.
"""

import json
import os
import sys

# When running outside Ghidra, use the mock module in this directory.
# Inside Ghidra, these imports are provided by the runtime.
try:
    from ghidra.program.model.listing import FunctionManager  # noqa: F401
    _IN_GHIDRA = True
except ImportError:
    _IN_GHIDRA = False
    sys.path.insert(0, os.path.dirname(__file__))
    from mock_ghidra import MockProgram


# ---------------------------------------------------------------------------
# Function extraction
# ---------------------------------------------------------------------------

def get_all_functions(program):
    """Collect all functions from the program's FunctionManager.

    Args:
        program: a Ghidra Program object (or MockProgram for testing).

    Returns:
        A list of dicts, each with keys:
            "name"    - str, the function name
            "address" - str, the entry point formatted as "0xNNNNNNNN"
            "size"    - int, the function body size in bytes
    """
    fm = program.getFunctionManager()
    functions = []
    for func in fm.getFunctions(True):
        functions.append({
            "name": func.getName(),
            "address": "0x" + format(int(str(func.getEntryPoint()), 16), "08x"),
            "size": func.getBody().getNumAddresses(),
        })
    return functions


def export_to_json(program, output_path):
    """Export function information to a JSON file.

    Args:
        program: a Ghidra Program object (or MockProgram for testing).
        output_path: file path for the output JSON.

    Returns:
        The data dict that was written (for testing convenience).
    """
    functions = get_all_functions(program)
    result = {
        "binary": program.getName(),
        "function_count": len(functions),
        "functions": functions,
    }
    with open(output_path, "w") as f:
        json.dump(result, f, indent=2)
    return result


# ---------------------------------------------------------------------------
# Ghidra entry point
# ---------------------------------------------------------------------------

def run():
    """Entry point when run as a Ghidra script."""
    if _IN_GHIDRA:
        # In real Ghidra, currentProgram is a global
        import __main__
        program = __main__.currentProgram
        out = os.path.join(os.path.expanduser("~"), "functions.json")
        data = export_to_json(program, out)
        print(f"Exported {data['function_count']} functions to {out}")


if __name__ == "__main__":
    run()
