#!/usr/bin/env python3
"""
test_lab.py -- Tests for the NID resolver.

Tests cover:
  - NID computation for known function names.
  - Database loading and lookup.
  - Verification of database entries against computed NIDs.
"""

import os
import sys

from nid_resolver import compute_nid, compute_nid_hex, NidDatabase

tests_run = 0
tests_passed = 0


def check(condition, msg):
    global tests_run, tests_passed
    tests_run += 1
    if condition:
        tests_passed += 1
    else:
        print(f"  FAIL: {msg}")
    # Without this, every test in this file passes under pytest no matter what
    # it found -- the counters are only read by the __main__ runner below, and
    # CI runs pytest. A check that cannot fail is not a check (Module 35).
    assert condition, msg


# ---------------------------------------------------------------------------
#  NID computation tests
# ---------------------------------------------------------------------------

def test_nid_computation():
    """Test that NID computation produces consistent 32-bit values."""
    print("--- test_nid_computation ---")

    # The NID should be deterministic.
    nid1 = compute_nid("cellGcmInit")
    nid2 = compute_nid("cellGcmInit")
    check(nid1 == nid2, "same input produces same NID")

    # Different names should (almost certainly) produce different NIDs.
    nid_a = compute_nid("printf")
    nid_b = compute_nid("malloc")
    check(nid_a != nid_b, "different inputs produce different NIDs")

    # NID should fit in 32 bits.
    check(0 <= nid1 <= 0xFFFFFFFF, "NID fits in 32 bits")

    # Hex formatting.
    hex_str = compute_nid_hex("cellGcmInit")
    check(hex_str.startswith("0x"), "hex string starts with 0x")
    check(len(hex_str) == 10, "hex string is 10 chars (0x + 8 hex digits)")


def test_nid_known_values():
    """
    Test NID computation against independently verifiable values.

    Since the algorithm is SHA-1 truncated to 4 bytes, we can verify
    by computing SHA-1 directly.
    """
    print("--- test_nid_known_values ---")

    import hashlib

    test_names = [
        "cellGcmInit",
        "sys_process_exit",
        "printf",
        "memcpy",
        "cellPadGetData",
    ]

    for name in test_names:
        # Compute NID using our function.
        nid = compute_nid(name)

        # Compute independently using hashlib directly.
        sha1 = hashlib.sha1(name.encode("utf-8")).digest()
        expected = int.from_bytes(sha1[:4], byteorder="big")

        check(nid == expected, f"NID for '{name}': got 0x{nid:08X}, expected 0x{expected:08X}")


# ---------------------------------------------------------------------------
#  Database tests
# ---------------------------------------------------------------------------

def test_database_load():
    """Test loading the NID database."""
    print("--- test_database_load ---")

    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nid_database.json")
    check(os.path.exists(db_path), "nid_database.json exists")

    db = NidDatabase()
    db.load(db_path)

    check(db.size > 0, "database has entries")
    check(db.size >= 30, f"database has at least 30 entries (got {db.size})")


def test_database_lookup():
    """Test looking up function names by NID."""
    print("--- test_database_lookup ---")

    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nid_database.json")
    db = NidDatabase()
    db.load(db_path)

    # Look up a name we know is in the database.
    nid = db.lookup_name("cellGcmInit")
    check(nid is not None, "cellGcmInit found in database")

    # Resolve that NID back.
    if nid is not None:
        results = db.resolve(nid)
        check(results is not None, "NID resolves to entries")
        if results:
            names = [r[1] for r in results]
            check("cellGcmInit" in names, "resolved name includes cellGcmInit")

    # Look up a name that should NOT be in the database.
    missing = db.lookup_name("thisDoesNotExist_12345")
    check(missing is None, "unknown function returns None")


def test_database_verification():
    """
    Verify that stored NIDs match computed NIDs for every entry.

    This catches any database entries where the NID was recorded
    incorrectly (not matching the SHA-1 computation).

    NOTE: The sample database may contain pre-computed NID values that
    were not generated by this script.  If entries fail verification,
    it means the stored NID does not match SHA-1(func_name)[:4].
    This is expected for some PS3 functions that use suffix versioning
    or non-standard hashing.
    """
    print("--- test_database_verification ---")

    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nid_database.json")
    db = NidDatabase()
    db.load(db_path)

    import hashlib

    # compute_nid must be the plain unsalted hash it claims to be.
    for name in ["printf", "malloc", "free", "memcpy", "memset", "strlen"]:
        expected = int.from_bytes(
            hashlib.sha1(name.encode("utf-8")).digest()[:4], "big")
        check(compute_nid(name) == expected,
              f"compute_nid('{name}') should be the first 4 bytes of SHA-1")

    # And now the point of the lab: not one entry in the shipped database is a
    # plain hash of its own name. Real PS3 NIDs are salted with a per-library
    # suffix before hashing, which is why looking a name up cannot be done by
    # hashing it and why the suffix TODO in nid_resolver.py exists at all.
    unsalted_hits = 0
    checked = 0
    for name in ["printf", "malloc", "free", "memcpy", "memset", "strlen"]:
        stored = db.lookup_name(name)
        if stored is None:
            continue
        checked += 1
        if stored == compute_nid(name):
            unsalted_hits += 1

    check(checked > 0, "the database should contain some of these names")
    check(unsalted_hits == 0,
          f"{unsalted_hits} of {checked} database NIDs matched an unsalted "
          f"hash -- if this ever fires, the database is synthetic, not real "
          f"PS3 data")


# ---------------------------------------------------------------------------
#  Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("NID Resolver -- Test Suite\n")

    test_nid_computation()
    test_nid_known_values()
    test_database_load()
    test_database_lookup()
    test_database_verification()

    print(f"\n{tests_passed} / {tests_run} tests passed.")
    sys.exit(0 if tests_passed == tests_run else 1)
