#!/usr/bin/env python3
"""
test_lab.py -- Tests for the NID resolver.

Tests cover:
  - NID computation for known function names.
  - Database loading and lookup.
  - Verification of database entries against computed NIDs.
"""

import os
import sys

from nid_resolver import compute_nid, compute_nid_hex, NidDatabase

tests_run = 0
tests_passed = 0


def check(condition, msg):
    global tests_run, tests_passed
    tests_run += 1
    if condition:
        tests_passed += 1
    else:
        print(f"  FAIL: {msg}")


# ---------------------------------------------------------------------------
#  NID computation tests
# ---------------------------------------------------------------------------

def test_nid_computation():
    """Test that NID computation produces consistent 32-bit values."""
    print("--- test_nid_computation ---")

    # The NID should be deterministic.
    nid1 = compute_nid("cellGcmInit")
    nid2 = compute_nid("cellGcmInit")
    check(nid1 == nid2, "same input produces same NID")

    # Different names should (almost certainly) produce different NIDs.
    nid_a = compute_nid("printf")
    nid_b = compute_nid("malloc")
    check(nid_a != nid_b, "different inputs produce different NIDs")

    # NID should fit in 32 bits.
    check(0 <= nid1 <= 0xFFFFFFFF, "NID fits in 32 bits")

    # Hex formatting.
    hex_str = compute_nid_hex("cellGcmInit")
    check(hex_str.startswith("0x"), "hex string starts with 0x")
    check(len(hex_str) == 10, "hex string is 10 chars (0x + 8 hex digits)")


def test_nid_known_values():
    """
    Test NID computation against independently verifiable values.

    Since the algorithm is SHA-1 truncated to 4 bytes, we can verify
    by computing SHA-1 directly.
    """
    print("--- test_nid_known_values ---")

    import hashlib

    test_names = [
        "cellGcmInit",
        "sys_process_exit",
        "printf",
        "memcpy",
        "cellPadGetData",
    ]

    for name in test_names:
        # Compute NID using our function.
        nid = compute_nid(name)

        # Compute independently using hashlib directly.
        sha1 = hashlib.sha1(name.encode("utf-8")).digest()
        expected = int.from_bytes(sha1[:4], byteorder="big")

        check(nid == expected, f"NID for '{name}': got 0x{nid:08X}, expected 0x{expected:08X}")


# ---------------------------------------------------------------------------
#  Database tests
# ---------------------------------------------------------------------------

def test_database_load():
    """Test loading the NID database."""
    print("--- test_database_load ---")

    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nid_database.json")
    check(os.path.exists(db_path), "nid_database.json exists")

    db = NidDatabase()
    db.load(db_path)

    check(db.size > 0, "database has entries")
    check(db.size >= 30, f"database has at least 30 entries (got {db.size})")


def test_database_lookup():
    """Test looking up function names by NID."""
    print("--- test_database_lookup ---")

    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nid_database.json")
    db = NidDatabase()
    db.load(db_path)

    # Look up a name we know is in the database.
    nid = db.lookup_name("cellGcmInit")
    check(nid is not None, "cellGcmInit found in database")

    # Resolve that NID back.
    if nid is not None:
        results = db.resolve(nid)
        check(results is not None, "NID resolves to entries")
        if results:
            names = [r[1] for r in results]
            check("cellGcmInit" in names, "resolved name includes cellGcmInit")

    # Look up a name that should NOT be in the database.
    missing = db.lookup_name("thisDoesNotExist_12345")
    check(missing is None, "unknown function returns None")


def test_database_verification():
    """
    Verify that stored NIDs match computed NIDs for every entry.

    This catches any database entries where the NID was recorded
    incorrectly (not matching the SHA-1 computation).

    NOTE: The sample database may contain pre-computed NID values that
    were not generated by this script.  If entries fail verification,
    it means the stored NID does not match SHA-1(func_name)[:4].
    This is expected for some PS3 functions that use suffix versioning
    or non-standard hashing.
    """
    print("--- test_database_verification ---")

    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nid_database.json")
    db = NidDatabase()
    db.load(db_path)

    # We test a few known-good names where the NID should definitely match.
    # (These use standard SHA-1 hashing with no suffix.)
    test_names = ["printf", "malloc", "free", "memcpy", "memset", "strlen"]

    import hashlib
    for name in test_names:
        stored_nid = db.lookup_name(name)
        if stored_nid is not None:
            computed = compute_nid(name)
            matches = (stored_nid == computed)
            check(
                matches,
                f"NID verification for '{name}': "
                f"stored=0x{stored_nid:08X}, computed=0x{computed:08X}"
            )
        # If not in database, skip (not a failure of the computation).


# ---------------------------------------------------------------------------
#  Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("NID Resolver -- Test Suite\n")

    test_nid_computation()
    test_nid_known_values()
    test_database_load()
    test_database_lookup()
    test_database_verification()

    print(f"\n{tests_passed} / {tests_run} tests passed.")
    sys.exit(0 if tests_passed == tests_run else 1)
