"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 33: N64 Display List Parser

Parse Fast3D display list commands from a binary dump.
"""

import sys
import os
import struct

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


# ---------------------------------------------------------------------------
# Command IDs
# ---------------------------------------------------------------------------

COMMAND_NAMES = {
    0x01: "G_MTX",
    0x03: "G_MOVEMEM",
    0x04: "G_VTX",
    0x05: "G_DL",
    0x06: "G_TRI1",
    0xB6: "G_CLEARGEOMETRYMODE",
    0xB7: "G_SETGEOMETRYMODE",
    0xB8: "G_ENDDL",
    0xB9: "G_SETOTHERMODE_L",
    0xBA: "G_SETOTHERMODE_H",
    0xBF: "G_TRI1_F3DEX",
    0xF3: "G_LOADBLOCK",
    0xF5: "G_SETTILE",
    0xFD: "G_SETTIMG",
}


# ---------------------------------------------------------------------------
# Command Parsing
# ---------------------------------------------------------------------------

def parse_command(data, offset):
    """Parse a single 8-byte display list command.

    Args:
        data: bytes of the display list binary.
        offset: byte offset of the command (must be 8-byte aligned).

    Returns:
        A dict with keys:
            "offset"   - int, byte offset in the data
            "cmd_id"   - int, the command byte (first byte)
            "cmd_name" - str, human-readable name (from COMMAND_NAMES)
            "raw"      - bytes, the full 8-byte command
            "params"   - dict, command-specific parsed parameters

        The "params" dict varies by command:

        G_VTX (0x04):
            "count" - int, number of vertices
            "addr"  - int, DRAM address (bytes 4-7 as big-endian uint32)

        G_TRI1 (0x06):
            "v0" - int, vertex index 0
            "v1" - int, vertex index 1
            "v2" - int, vertex index 2

        G_DL (0x05):
            "addr" - int, address of sub-display list

        G_SETTIMG (0xFD):
            "addr" - int, texture DRAM address

        All other commands:
            "word0" - int, first 4 bytes as big-endian uint32
            "word1" - int, last 4 bytes as big-endian uint32

        Returns None if there are fewer than 8 bytes remaining.
    """
    if offset + 8 > len(data):
        return None

    raw = bytes(data[offset:offset + 8])
    cmd_id = raw[0]
    cmd_name = COMMAND_NAMES.get(cmd_id, "UNKNOWN")

    if cmd_id == 0x04:          # G_VTX
        params = {
            "count": (data[offset + 1] >> 4) & 0x0F,
            "addr": struct.unpack_from(">I", data, offset + 4)[0],
        }
    elif cmd_id == 0x06:        # G_TRI1 -- indices are stored pre-multiplied by 2
        params = {
            "v0": data[offset + 5] // 2,
            "v1": data[offset + 6] // 2,
            "v2": data[offset + 7] // 2,
        }
    elif cmd_id in (0x05, 0xFD):    # G_DL, G_SETTIMG
        params = {"addr": struct.unpack_from(">I", data, offset + 4)[0]}
    else:
        params = {
            "word0": struct.unpack_from(">I", data, offset)[0],
            "word1": struct.unpack_from(">I", data, offset + 4)[0],
        }

    return {
        "offset": offset,
        "cmd_id": cmd_id,
        "cmd_name": cmd_name,
        "raw": raw,
        "params": params,
    }


def parse_display_list(data):
    """Parse a complete display list binary.

    Decodes 8-byte commands sequentially. Stops at the end of data
    or when a G_ENDDL (0xB8) command is encountered (inclusive --
    include the ENDDL in the results).

    Args:
        data: bytes of the display list.

    Returns:
        A list of parsed command dicts (from parse_command).
    """
    commands = []
    offset = 0
    while offset + 8 <= len(data):
        cmd = parse_command(data, offset)
        if cmd is None:
            break
        commands.append(cmd)
        offset += 8
        if cmd["cmd_id"] == 0xB8:       # G_ENDDL terminates the list
            break
    return commands


def format_command(cmd):
    """Format a parsed command for display.

    Args:
        cmd: dict from parse_command().

    Returns:
        A string like "0000: G_VTX       count=4, addr=0x06000000"
    """
    prefix = f"{cmd['offset']:04X}: {cmd['cmd_name']:20s}"
    params = cmd["params"]
    name = cmd["cmd_name"]

    if name == "G_VTX":
        return prefix + f"count={params['count']}, addr=0x{params['addr']:08X}"
    if name == "G_TRI1":
        return prefix + f"v0={params['v0']}, v1={params['v1']}, v2={params['v2']}"
    if "addr" in params:
        return prefix + f"addr=0x{params['addr']:08X}"
    return prefix + f"word0=0x{params['word0']:08X}, word1=0x{params['word1']:08X}"


def summarize(commands):
    """Produce a summary counting each command type.

    Args:
        commands: list of parsed command dicts.

    Returns:
        A dict mapping command name (str) -> count (int).
    """
    counts = {}
    for cmd in commands:
        counts[cmd["cmd_name"]] = counts.get(cmd["cmd_name"], 0) + 1
    return counts


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # Example display list: VTX, TRI1, TRI1, ENDDL
    dlist = bytes([
        # G_VTX: count=4, addr=0x06000000
        0x04, 0x40, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00,
        # G_TRI1: v0=0, v1=1, v2=2
        0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x04,
        # G_TRI1: v0=0, v1=2, v2=3
        0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x06,
        # G_ENDDL
        0xB8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    ])

    commands = parse_display_list(dlist)
    if commands is None:
        print("parse_display_list() returned None -- implement the TODO sections.")
        return

    for cmd in commands:
        line = format_command(cmd)
        if line:
            print(line)

    print()
    summary = summarize(commands)
    if summary:
        print("Summary:")
        for name, count in sorted(summary.items()):
            print(f"  {name}: {count}")


if __name__ == "__main__":
    main()
