"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 66: Divergence Minimiser

Shrink a long failing input to a minimal reproducer by truncation and
backward bisection.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


def truncate(inputs, index):
    """Return inputs up to and including *index*.

    Args:
        inputs: the sequence.
        index: 0-based index of the failing step.

    Returns:
        A new list. An index beyond the end returns the whole sequence; a
        negative index returns an empty list.
    """
    if index < 0:
        return []
    return list(inputs[:index + 1])


def shrink_prefix(inputs, still_fails):
    """Remove as much of the leading input as possible.

    Binary search for the largest prefix that can be dropped while the
    remainder still fails.

    Args:
        inputs: the sequence (already truncated).
        still_fails: callable(sequence) -> bool.

    Returns:
        The shortest suffix found that still fails. If dropping nothing is the
        only option, returns the input unchanged.
    """
    current = list(inputs)
    lo, hi = 0, len(current)      # number of leading elements to drop
    best = 0
    while lo <= hi:
        mid = (lo + hi) // 2
        if mid < len(current) and still_fails(current[mid:]):
            best = mid
            lo = mid + 1
        else:
            hi = mid - 1
    return current[best:]


def shrink_elements(inputs, still_fails):
    """Remove individual inputs that are not needed.

    Walks from the end to the start, trying to delete each element and keeping
    the deletion when the sequence still fails. Iterating backwards keeps the
    indices of the not-yet-visited elements stable.

    Returns:
        A list with the unnecessary elements removed.
    """
    current = list(inputs)
    for i in range(len(current) - 1, -1, -1):
        trial = current[:i] + current[i + 1:]
        if still_fails(trial):
            current = trial
    return current


def minimise(inputs, still_fails, failure_index=None):
    """Run the whole minimisation procedure.

    Order: truncate (if a failure index is given), then shrink the prefix,
    then shrink individual elements.

    Returns:
        A dict with:
            "minimal"  - the reduced sequence
            "original" - the original length
            "final"    - the reduced length
            "ratio"    - final / original, 0.0 if original was empty
            "log"      - list of (stage_name, length_after) tuples

    Raises:
        ValueError: if the input does not fail to begin with, or if any stage
            produces a sequence that no longer fails. A minimiser that loses
            the bug has produced a different one.
    """
    original = list(inputs)
    if not still_fails(original):
        raise ValueError("input does not reproduce the failure")

    log = []
    current = original

    if failure_index is not None:
        current = truncate(current, failure_index)
        if not still_fails(current):
            raise ValueError("truncation lost the failure")
        log.append(("truncate", len(current)))

    current = shrink_prefix(current, still_fails)
    if not still_fails(current):
        raise ValueError("prefix shrink lost the failure")
    log.append(("shrink_prefix", len(current)))

    current = shrink_elements(current, still_fails)
    if not still_fails(current):
        raise ValueError("element shrink lost the failure")
    log.append(("shrink_elements", len(current)))

    return {
        "minimal": current,
        "original": len(original),
        "final": len(current),
        "ratio": (len(current) / len(original)) if original else 0.0,
        "log": log,
    }


def format_result(result):
    """Format a minimisation result."""
    lines = [f"minimised {result['original']} -> {result['final']} "
             f"({result['ratio'] * 100:.1f}% of original)"]
    for stage, length in result["log"]:
        lines.append(f"  after {stage:16s} {length}")
    return "\n".join(lines)
