"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 27: ARM/Thumb Disassembler

Disassemble ARM and Thumb code using Capstone, with mode detection.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from capstone import Cs, CS_ARCH_ARM, CS_MODE_ARM, CS_MODE_THUMB


# ---------------------------------------------------------------------------
# Disassembly helpers
# ---------------------------------------------------------------------------

def disasm_arm(data, base_address=0):
    """Disassemble a binary blob as ARM (32-bit) instructions.

    Args:
        data: bytes of ARM machine code.
        base_address: address of the first byte.

    Returns:
        A list of tuples: (address, mnemonic, op_str, raw_bytes)
        where raw_bytes is the bytes of the instruction.
    """
    cs = Cs(CS_ARCH_ARM, CS_MODE_ARM)
    return [
        (insn.address, insn.mnemonic, insn.op_str, insn.bytes)
        for insn in cs.disasm(data, base_address)
    ]


def disasm_thumb(data, base_address=0):
    """Disassemble a binary blob as Thumb (16-bit) instructions.

    Args:
        data: bytes of Thumb machine code.
        base_address: address of the first byte.

    Returns:
        A list of tuples: (address, mnemonic, op_str, raw_bytes)
    """
    cs = Cs(CS_ARCH_ARM, CS_MODE_THUMB)
    return [
        (insn.address, insn.mnemonic, insn.op_str, insn.bytes)
        for insn in cs.disasm(data, base_address)
    ]


def format_disasm(instructions, mode_label="ARM"):
    """Format a list of disassembled instructions for display.

    Args:
        instructions: list of (address, mnemonic, op_str, raw_bytes) tuples.
        mode_label: "ARM" or "THUMB" to prefix each line.

    Returns:
        A list of formatted strings like:
        "[ARM]   0x08000000: mov   r0, #0x42"
    """
    return [
        f"[{mode_label:5s}] 0x{addr:08X}: {mnemonic:6s} {op_str}"
        for addr, mnemonic, op_str, _raw in instructions
    ]


def detect_mode_switches(instructions):
    """Scan disassembled instructions for BX (Branch and Exchange).

    A BX instruction switches between ARM and Thumb mode. The target
    register's bit 0 determines the mode, but since we don't know
    register values at static analysis time, we just report that a
    mode switch *could* happen.

    Args:
        instructions: list of (address, mnemonic, op_str, raw_bytes) tuples.

    Returns:
        A list of dicts with keys:
            "address"  - int, address of the BX instruction
            "register" - str, the register name (e.g. "r0", "lr")
    """
    return [
        {"address": addr, "register": op_str.strip()}
        for addr, mnemonic, op_str, _raw in instructions
        if mnemonic.lower() == "bx"
    ]


def disasm_auto(sections, base_address=0):
    """Disassemble multiple sections with explicit mode annotations.

    This is a simplified version of automatic mode tracking. Instead of
    trying to follow BX targets (which requires runtime register values),
    the caller provides sections with their mode.

    Args:
        sections: list of dicts, each with:
            "data"    - bytes of machine code
            "offset"  - int, byte offset from base_address
            "mode"    - str, "arm" or "thumb"

    Returns:
        A list of formatted strings with mode labels.
    """
    lines = []
    for section in sections:
        addr = base_address + section["offset"]
        if section["mode"] == "thumb":
            decoded = disasm_thumb(section["data"], addr)
            label = "THUMB"
        else:
            decoded = disasm_arm(section["data"], addr)
            label = "ARM"
        lines.extend(format_disasm(decoded, label))
    return lines


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # Example ARM code: MOV R0, #0x42; BX LR
    arm_code = bytes([
        0x42, 0x00, 0xA0, 0xE3,    # MOV R0, #0x42
        0x1E, 0xFF, 0x2F, 0xE1,    # BX LR
    ])

    # Example Thumb code: MOVS R0, #0; ADDS R0, #1; BX LR
    thumb_code = bytes([
        0x00, 0x20,     # MOVS R0, #0
        0x01, 0x30,     # ADDS R0, #1
        0x70, 0x47,     # BX LR
    ])

    print("=== ARM Mode ===")
    arm_insns = disasm_arm(arm_code, base_address=0x08000000)
    if arm_insns:
        for line in format_disasm(arm_insns, "ARM"):
            print(line)
    else:
        print("disasm_arm() returned None -- implement the TODO sections.")

    print("\n=== Thumb Mode ===")
    thumb_insns = disasm_thumb(thumb_code, base_address=0x08000100)
    if thumb_insns:
        for line in format_disasm(thumb_insns, "THUMB"):
            print(line)
    else:
        print("disasm_thumb() returned None -- implement the TODO sections.")


if __name__ == "__main__":
    main()
