"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 23: CFG Builder (Recursive Descent)

Build a control-flow graph from SimpleISA bytecode using recursive
descent disassembly.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.dirname(__file__))

from simple_isa import (
    decode_one, format_instruction,
    BRANCH_OPCODES, JUMP_OPCODES, FALLTHROUGH_OPCODES, TERMINATOR_OPCODES,
)


# ---------------------------------------------------------------------------
# Basic Block
# ---------------------------------------------------------------------------

class BasicBlock:
    """A straight-line sequence of instructions with edges to successors.

    Attributes:
        start_addr: int, address of the first instruction.
        instructions: list of decoded instruction dicts.
        successors: list of (target_addr, edge_label) tuples.
                    edge_label is "fall" for fall-through, "taken" for
                    branch/jump targets.
    """

    def __init__(self, start_addr):
        self.start_addr = start_addr
        self.instructions = []
        self.successors = []

    def end_addr(self):
        """Address just past the last instruction in this block."""
        if not self.instructions:
            return self.start_addr
        last = self.instructions[-1]
        return last["address"] + last["length"]

    def label(self):
        return f"blk_{self.start_addr:04X}"

    def __repr__(self):
        return f"BasicBlock(0x{self.start_addr:04X}, {len(self.instructions)} instrs)"


# ---------------------------------------------------------------------------
# CFG Construction
# ---------------------------------------------------------------------------

def build_cfg(data, entry_point=0):
    """Build a control-flow graph via recursive descent disassembly.

    Starting at *entry_point*, decode instructions sequentially until
    a branch/jump/return is hit, forming a basic block. Then recursively
    follow branch targets and fall-through addresses to discover more
    blocks.

    Args:
        data: bytes, the program image.
        entry_point: int, address to start disassembly.

    Returns:
        A dict mapping start_address (int) -> BasicBlock.
    """
    cfg = {}
    worklist = [entry_point]

    while worklist:
        addr = worklist.pop()
        if addr in cfg:
            continue

        block = BasicBlock(addr)
        cursor = addr
        last = None

        while True:
            instr = decode_one(data, cursor)
            if instr is None:
                break
            block.instructions.append(instr)
            cursor += instr["length"]
            last = instr
            if instr["opcode"] in BRANCH_OPCODES:
                break

        if last is not None:
            opcode = last["opcode"]
            if opcode in JUMP_OPCODES and last["operand"] is not None:
                target = last["operand"]
                block.successors.append((target, "taken"))
                worklist.append(target)
            if opcode in FALLTHROUGH_OPCODES:
                block.successors.append((cursor, "fall"))
                worklist.append(cursor)

        cfg[addr] = block

    return cfg


def cfg_to_dot(cfg):
    """Convert a CFG dict to Graphviz DOT format.

    Args:
        cfg: dict of start_address -> BasicBlock.

    Returns:
        A string containing valid DOT source.
    """
    lines = ["digraph CFG {"]
    lines.append('  node [shape=box, fontname="Courier"];')

    for addr in sorted(cfg):
        block = cfg[addr]
        body = "\n".join(format_instruction(i) for i in block.instructions)
        lines.append(f'  "{block.label()}" [label="{body}"];')

    for addr in sorted(cfg):
        block = cfg[addr]
        for target, edge in block.successors:
            target_label = cfg[target].label() if target in cfg else f"blk_{target:04X}"
            lines.append(f'  "{block.label()}" -> "{target_label}" [label="{edge}"];')

    lines.append("}")
    return "\n".join(lines) + "\n"


def print_cfg(cfg):
    """Print a textual summary of the CFG."""
    for addr in sorted(cfg):
        block = cfg[addr]
        print(f"--- Block 0x{addr:04X} ---")
        for instr in block.instructions:
            print(f"  {format_instruction(instr)}")
        if block.successors:
            targets = ", ".join(
                f"0x{t:04X} ({lbl})" for t, lbl in block.successors
            )
            print(f"  -> {targets}")
        else:
            print("  -> (end)")
        print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # Example program:
    #   0000: LOAD r0
    #   0002: BEQ 0006
    #   0005: STORE r1    (fall-through from BEQ)
    #   0007: JMP 0009    (skip to end -- note: this is 3 bytes, target 0x0009)
    #   0009: RET         (branch target and jump target merge here)
    #
    # Note: BEQ target 0x0006 is actually a STORE at 0x0005?
    # Let's fix the addresses to be consistent:
    program = bytes([
        0x02, 0x00,             # 0000: LOAD r0
        0x06, 0x07, 0x00,       # 0002: BEQ 0007
        0x03, 0x01,             # 0005: STORE r1
        0x08,                   # 0007: RET
    ])

    cfg = build_cfg(program, entry_point=0)
    if cfg is None:
        print("build_cfg() returned None -- implement the TODO sections.")
        return

    print_cfg(cfg)
    print("=== DOT Output ===")
    dot = cfg_to_dot(cfg)
    if dot:
        print(dot)
    else:
        print("cfg_to_dot() returned None -- implement it.")


if __name__ == "__main__":
    main()
