"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 46: Capstone Multi-Arch Analyzer

Auto-detect the CPU architecture of a binary blob by trying multiple
Capstone disassembly configurations.
"""

try:
    from capstone import (
        Cs, CS_ARCH_X86, CS_ARCH_ARM, CS_ARCH_ARM64, CS_ARCH_MIPS,
        CS_ARCH_PPC, CS_MODE_32, CS_MODE_64, CS_MODE_ARM, CS_MODE_THUMB,
        CS_MODE_MIPS32, CS_MODE_BIG_ENDIAN, CS_MODE_LITTLE_ENDIAN,
    )
    HAS_CAPSTONE = True
except ImportError:
    HAS_CAPSTONE = False

# ---------------------------------------------------------------------------
# Architecture candidates
# ---------------------------------------------------------------------------

# Each candidate is (name, arch_const, mode_const).
# Used when Capstone is available.
CANDIDATES = []
if HAS_CAPSTONE:
    CANDIDATES = [
        ("x86_32",    CS_ARCH_X86,   CS_MODE_32),
        ("x86_64",    CS_ARCH_X86,   CS_MODE_64),
        ("arm32",     CS_ARCH_ARM,   CS_MODE_ARM),
        ("arm_thumb", CS_ARCH_ARM,   CS_MODE_THUMB),
        ("arm64",     CS_ARCH_ARM64, CS_MODE_ARM),
        ("mips32_be", CS_ARCH_MIPS,  CS_MODE_MIPS32 | CS_MODE_BIG_ENDIAN),
        ("mips32_le", CS_ARCH_MIPS,  CS_MODE_MIPS32 | CS_MODE_LITTLE_ENDIAN),
        ("ppc32_be",  CS_ARCH_PPC,   CS_MODE_32 | CS_MODE_BIG_ENDIAN),
    ]


# ---------------------------------------------------------------------------
# Scoring functions -- complete the TODOs
# ---------------------------------------------------------------------------

def compute_score(decoded_bytes, total_bytes, num_instructions):
    """Compute a disassembly quality score.

    Parameters
    ----------
    decoded_bytes : int
        Total bytes that were part of valid instructions.
    total_bytes : int
        Total bytes in the input blob.
    num_instructions : int
        Number of successfully decoded instructions.

    Returns
    -------
    dict with keys:
        "byte_ratio"      : float  -- decoded_bytes / total_bytes (0.0 if total is 0)
        "num_instructions" : int
        "decoded_bytes"    : int
    """
    return {
        "byte_ratio": (decoded_bytes / total_bytes) if total_bytes else 0.0,
        "num_instructions": num_instructions,
        "decoded_bytes": decoded_bytes,
    }


def try_disassemble(data, arch, mode):
    """Try disassembling *data* with the given Capstone arch/mode.

    Parameters
    ----------
    data : bytes
        Raw binary data.
    arch : int
        Capstone architecture constant (e.g. CS_ARCH_X86).
    mode : int
        Capstone mode constant (e.g. CS_MODE_32).

    Returns
    -------
    dict
        Score dict from compute_score.

    Requires Capstone to be installed.
    """
    md = Cs(arch, mode)
    instructions = list(md.disasm(data, 0))
    decoded_bytes = sum(insn.size for insn in instructions)
    return compute_score(decoded_bytes, len(data), len(instructions))


def analyze(data, candidates=None):
    """Analyze a binary blob and return ranked architecture guesses.

    Parameters
    ----------
    data : bytes
        Raw binary data to analyze.
    candidates : list of tuple, optional
        Override the default CANDIDATES list.  Each tuple is
        (name, arch, mode).

    Returns
    -------
    list of dict
        Sorted by byte_ratio descending (then num_instructions desc).
        Each dict has:
            "name"             : str
            "byte_ratio"       : float
            "num_instructions" : int
            "decoded_bytes"    : int
    """
    if candidates is None:
        candidates = CANDIDATES

    results = []
    for name, arch, mode in candidates:
        score = try_disassemble(data, arch, mode)
        results.append(dict(score, name=name))

    results.sort(key=lambda r: (-r["byte_ratio"], -r["num_instructions"]))
    return results


def best_guess(data, candidates=None):
    """Return the best architecture guess for *data*.

    Returns
    -------
    dict or None
        The top-ranked result from analyze(), or None if no candidates.
    """
    results = analyze(data, candidates)
    return results[0] if results else None


# ---------------------------------------------------------------------------
# Mock disassembly (for testing without Capstone)
# ---------------------------------------------------------------------------

def compute_score_from_mock(insn_sizes, total_bytes):
    """Compute a score from a list of instruction sizes.

    This allows testing the scoring logic without Capstone.

    Parameters
    ----------
    insn_sizes : list of int
        Size of each decoded instruction.
    total_bytes : int
        Total input size.

    Returns
    -------
    dict
        Score dict.
    """
    decoded = sum(insn_sizes)
    return compute_score(decoded, total_bytes, len(insn_sizes))


def rank_mock_results(results):
    """Rank a list of (name, score_dict) tuples.

    Parameters
    ----------
    results : list of (str, dict)

    Returns
    -------
    list of dict
        Sorted by (-byte_ratio, -num_instructions), with "name" added.
    """
    ranked = [dict(score, name=name) for name, score in results]
    ranked.sort(key=lambda r: (-r["byte_ratio"], -r["num_instructions"]))
    return ranked


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python multi_arch_analyzer.py <binary_file>")
        sys.exit(1)

    if not HAS_CAPSTONE:
        print("Error: capstone package not installed (pip install capstone)")
        sys.exit(1)

    with open(sys.argv[1], "rb") as f:
        blob = f.read()

    results = analyze(blob)
    print(f"Analyzing {len(blob)} bytes...\n")
    for i, r in enumerate(results):
        print(f"  {i+1}. {r['name']:<12s}  "
              f"ratio={r['byte_ratio']:.3f}  "
              f"insns={r['num_instructions']}  "
              f"decoded={r['decoded_bytes']}")
    if results:
        print(f"\nBest guess: {results[0]['name']}")
