"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 61: Attribution Harness

Count what the guest did and what your harness did, separately, so a
screenshot stops being the only evidence you have.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


GUEST = "guest"
HARNESS = "harness"
SOURCES = (GUEST, HARNESS)


class Attribution:
    """Counts draws and dispatches, tagged by who caused them."""

    def __init__(self):
        self.frame = {"draws": {GUEST: 0, HARNESS: 0},
                      "dispatch": {"native": 0, "fallback": 0}}
        self.session = {"draws": {GUEST: 0, HARNESS: 0},
                        "dispatch": {"native": 0, "fallback": 0},
                        "frames": 0}

    def record_draw(self, source, count=1):
        """Record *count* draw calls attributed to *source*.

        Args:
            source: GUEST or HARNESS.
            count: how many draws.

        Raises:
            ValueError: on an unknown source. A draw you cannot attribute is
                worse than one you did not count -- it is the exact ambiguity
                this harness exists to remove.
        """
        if source not in SOURCES:
            raise ValueError(f"unknown draw source {source!r}")
        self.frame["draws"][source] += count
        self.session["draws"][source] += count

    def record_dispatch(self, native):
        """Record one dispatch.

        Args:
            native: True if a recompiled function ran, False if it fell back
                to an interpreter, emulator, or stub.
        """
        key = "native" if native else "fallback"
        self.frame["dispatch"][key] += 1
        self.session["dispatch"][key] += 1

    def end_frame(self):
        """Close the current frame and return its summary.

        Returns:
            A dict with "draws" and "dispatch" sub-dicts for this frame only.

        The frame counters reset afterwards; the session counters do not.
        """
        snapshot = {
            "draws": dict(self.frame["draws"]),
            "dispatch": dict(self.frame["dispatch"]),
        }
        self.session["frames"] += 1
        self.frame = {"draws": {GUEST: 0, HARNESS: 0},
                      "dispatch": {"native": 0, "fallback": 0}}
        return snapshot

    def session_summary(self):
        """Return session totals plus the derived ratios.

        Returns:
            A dict with:
                "frames"          - int
                "draws"           - {GUEST: int, HARNESS: int}
                "dispatch"        - {"native": int, "fallback": int}
                "guest_draw_ratio" - guest draws / total draws, 0.0 if none
                "native_ratio"     - native / total dispatches, 0.0 if none
        """
        draws = dict(self.session["draws"])
        dispatch = dict(self.session["dispatch"])
        total_draws = draws[GUEST] + draws[HARNESS]
        total_dispatch = dispatch["native"] + dispatch["fallback"]
        return {
            "frames": self.session["frames"],
            "draws": draws,
            "dispatch": dispatch,
            "guest_draw_ratio": (draws[GUEST] / total_draws) if total_draws else 0.0,
            "native_ratio": (dispatch["native"] / total_dispatch) if total_dispatch else 0.0,
        }


def honest_claim(summary):
    """Return a claim about the evidence that refuses to overstate it.

    Rules, checked in this order:

      - No draws at all            -> "Nothing has been drawn."
      - No guest draws             -> "All N draws came from the harness; the
                                       guest has not drawn anything."
      - Some guest draws           -> "X of N draws came from guest code
                                       (P%); the rest are harness."
      - All draws from guest       -> "All N draws came from guest code."

    Then, if any dispatches were recorded, append one sentence:

      - fallback == 0  -> " All N dispatches ran native code."
      - otherwise      -> " F of N dispatches fell back."

    Returns:
        A string.
    """
    guest = summary["draws"][GUEST]
    harness = summary["draws"][HARNESS]
    total = guest + harness

    if total == 0:
        claim = "Nothing has been drawn."
    elif guest == 0:
        claim = (f"All {total} draws came from the harness; "
                 f"the guest has not drawn anything.")
    elif harness == 0:
        claim = f"All {total} draws came from guest code."
    else:
        pct = round(100 * guest / total)
        claim = (f"{guest} of {total} draws came from guest code "
                 f"({pct}%); the rest are harness.")

    native = summary["dispatch"]["native"]
    fallback = summary["dispatch"]["fallback"]
    dispatched = native + fallback
    if dispatched:
        if fallback == 0:
            claim += f" All {dispatched} dispatches ran native code."
        else:
            claim += f" {fallback} of {dispatched} dispatches fell back."

    return claim
