"""REFERENCE SOLUTION -- generated by tools/make_solutions.py.

Do not edit by hand: edit the implementation in that script and regenerate.
Try the exercise before reading this one.
"""

"""
Lab 41: TEV Stage Compiler

Translate GameCube TEV (Texture Environment) stage configurations into GLSL.
"""

import json


# ---------------------------------------------------------------------------
# Input source mapping
# ---------------------------------------------------------------------------

# Maps TEV input names to GLSL expressions.
# Color (vec3) sources:
COLOR_SOURCES = {
    "zero":     "vec3(0.0)",
    "one":      "vec3(1.0)",
    "half":     "vec3(0.5)",
    "tex0_rgb": "t0.rgb",
    "tex1_rgb": "t1.rgb",
    "ras_rgb":  "v_color.rgb",
    "prev_rgb": "prev.rgb",
}

# Alpha (float) sources:
ALPHA_SOURCES = {
    "zero":    "0.0",
    "one":     "1.0",
    "half":    "0.5",
    "tex0_a":  "t0.a",
    "tex1_a":  "t1.a",
    "ras_a":   "v_color.a",
    "prev_a":  "prev.a",
}


# ---------------------------------------------------------------------------
# Code generation helpers -- complete the TODOs
# ---------------------------------------------------------------------------

def resolve_color_input(name):
    """Resolve a color input name to its GLSL expression.

    Parameters
    ----------
    name : str
        A key from COLOR_SOURCES.

    Returns
    -------
    str
        The corresponding GLSL expression.

    Raises
    ------
    ValueError
        If the name is not recognized.
    """
    if name not in COLOR_SOURCES:
        raise ValueError(f"Unknown color input: {name}")
    return COLOR_SOURCES[name]


def resolve_alpha_input(name):
    """Resolve an alpha input name to its GLSL expression.

    Parameters
    ----------
    name : str
        A key from ALPHA_SOURCES.

    Returns
    -------
    str
        The corresponding GLSL expression.

    Raises
    ------
    ValueError
        If the name is not recognized.
    """
    if name not in ALPHA_SOURCES:
        raise ValueError(f"Unknown alpha input: {name}")
    return ALPHA_SOURCES[name]


def emit_tev_color(stage_idx, inputs, op):
    """Emit the GLSL statement for one TEV stage's color calculation.

    Parameters
    ----------
    stage_idx : int
        Stage number (for the comment).
    inputs : dict
        {"a": str, "b": str, "c": str, "d": str} -- input source names.
    op : str
        "add" or "sub".

    Returns
    -------
    str
        Indented GLSL statement like:
        '    prev.rgb = d + mix(a, b, c);'    (for op "add")
        '    prev.rgb = d - mix(a, b, c);'    (for op "sub")

    The mix() function in GLSL computes: mix(x, y, a) = x*(1-a) + y*a
    which matches the TEV formula: (1-c)*a + c*b = mix(a, b, c).
    """
    a = resolve_color_input(inputs["a"])
    b = resolve_color_input(inputs["b"])
    c = resolve_color_input(inputs["c"])
    d = resolve_color_input(inputs["d"])
    # TEV computes d +/- ((1-c)*a + c*b), which is exactly GLSL mix(a, b, c).
    sign = "-" if op == "sub" else "+"
    return f"    prev.rgb = {d} {sign} mix({a}, {b}, {c});"


def emit_tev_alpha(stage_idx, inputs, op):
    """Emit the GLSL statement for one TEV stage's alpha calculation.

    Same formula as color but with float values instead of vec3.

    Returns
    -------
    str
        Indented GLSL statement like:
        '    prev.a = d + mix(a, b, c);'
    """
    a = resolve_alpha_input(inputs["a"])
    b = resolve_alpha_input(inputs["b"])
    c = resolve_alpha_input(inputs["c"])
    d = resolve_alpha_input(inputs["d"])
    sign = "-" if op == "sub" else "+"
    return f"    prev.a = {d} {sign} mix({a}, {b}, {c});"


def emit_stage(stage_idx, stage):
    """Emit all GLSL lines for one TEV stage.

    Parameters
    ----------
    stage_idx : int
        Stage number.
    stage : dict
        {
            "color_inputs": {"a": ..., "b": ..., "c": ..., "d": ...},
            "color_op": "add" or "sub",
            "alpha_inputs": {"a": ..., "b": ..., "c": ..., "d": ...},
            "alpha_op": "add" or "sub"
        }

    Returns
    -------
    list of str
        Lines of GLSL code for this stage (including comment header).
    """
    return [
        f"    // TEV Stage {stage_idx}",
        emit_tev_color(stage_idx, stage["color_inputs"], stage["color_op"]),
        emit_tev_alpha(stage_idx, stage["alpha_inputs"], stage["alpha_op"]),
    ]


def compile_tev(config):
    """Compile a TEV configuration into a complete GLSL fragment shader.

    Parameters
    ----------
    config : dict
        {
            "stages": [ ... ],
            "textures": [0, 1, ...]
        }

    Returns
    -------
    str
        Complete GLSL fragment shader source.
    """
    textures = config.get("textures", [])
    lines = [
        "#version 330 core",
        "",
        "in vec2 v_texcoord;",
        "in vec4 v_color;",
    ]
    for i in textures:
        lines.append(f"uniform sampler2D u_tex{i};")
    lines.append("out vec4 frag_color;")
    lines.append("")
    lines.append("void main() {")
    for i in textures:
        lines.append(f"    vec4 t{i} = texture(u_tex{i}, v_texcoord);")
    lines.append("    vec4 prev = vec4(0.0);")
    for idx, stage in enumerate(config.get("stages", [])):
        lines.extend(emit_stage(idx, stage))
    lines.append("    frag_color = clamp(prev, 0.0, 1.0);")
    lines.append("}")
    return "\n".join(lines)


def compile_tev_json(json_str):
    """Convenience: parse JSON string and compile."""
    return compile_tev(json.loads(json_str))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    sample = {
        "stages": [
            {
                "color_inputs": {"a": "tex0_rgb", "b": "zero", "c": "zero", "d": "zero"},
                "color_op": "add",
                "alpha_inputs": {"a": "tex0_a", "b": "zero", "c": "zero", "d": "zero"},
                "alpha_op": "add",
            },
        ],
        "textures": [0],
    }
    print(compile_tev(sample))
